// Interval is the wire form of a Postgres INTERVAL column.
//
// # Why not google.protobuf.Duration
//
// Duration is seconds plus nanos — one magnitude. A Postgres interval is
// three, and they are not interconvertible: '1 mon' is 28, 29, 30 or 31 days
// depending on which month it is added to, and '1 day' is 23, 24 or 25 hours
// across a daylight-saving boundary. Postgres keeps months, days and
// microseconds apart precisely so it does not have to guess, and pgtype.Interval
// mirrors that.
//
// Collapsing them to a Duration would mean picking a month length at the wire
// boundary and writing the guess into the caller's data. For a layer whose job
// is to be faithful to what Postgres stores, that is the wrong trade at any
// price — so the wire type mirrors the storage type instead.
//
// # What this replaces
//
// Before this existed, `interval` had four different representations and no two
// agreed: coltype.ProtoType said google.protobuf.Duration, coltype.GoType said
// time.Duration, coltype.ScanFragments declared a `string` and assigned it
// straight to the proto field, and the dynamic dispatcher published TYPE_STRING.
// The generated code did not compile, which is why nobody had noticed that the
// four disagreed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlantis/common/v1/interval.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interval carries the three components Postgres stores, unmodified.
//
// The signs are independent and all three may be negative: '1 mon -3 days' is a
// legal interval and round-trips as months=1, days=-3.
type Interval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whole months. Years are months*12 — Postgres normalizes '1 year' to
	// 12 months on input, so no separate field is needed.
	Months int32 `protobuf:"varint,1,opt,name=months" json:"months,omitempty"`
	// Whole days, kept apart from microseconds because a day is not always
	// 86_400_000_000 microseconds.
	Days int32 `protobuf:"varint,2,opt,name=days" json:"days,omitempty"`
	// Everything below a day: hours, minutes, seconds and fractional seconds,
	// as a single microsecond count. Postgres stores this resolution exactly,
	// and int64 microseconds covers the full range it accepts.
	Microseconds  int64 `protobuf:"varint,3,opt,name=microseconds" json:"microseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_atlantis_common_v1_interval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_interval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_interval_proto_rawDescGZIP(), []int{0}
}

func (x *Interval) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *Interval) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *Interval) GetMicroseconds() int64 {
	if x != nil {
		return x.Microseconds
	}
	return 0
}

var File_atlantis_common_v1_interval_proto protoreflect.FileDescriptor

const file_atlantis_common_v1_interval_proto_rawDesc = "" +
	"\n" +
	"!atlantis/common/v1/interval.proto\x12\x12atlantis.common.v1\"Z\n" +
	"\bInterval\x12\x16\n" +
	"\x06months\x18\x01 \x01(\x05R\x06months\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\"\n" +
	"\fmicroseconds\x18\x03 \x01(\x03R\fmicrosecondsB\xf7\x01\n" +
	"\x16com.atlantis.common.v1B\rIntervalProtoP\x01Z_github.com/rachitkumar205/atlantis/internal/codegen/compilecheck/pb/atlantis/common/v1;commonv1\xa2\x02\x03ACX\xaa\x02\x12Atlantis.Common.V1\xca\x02\x12Atlantis\\Common\\V1\xe2\x02\x1eAtlantis\\Common\\V1\\GPBMetadata\xea\x02\x14Atlantis::Common::V1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_atlantis_common_v1_interval_proto_rawDescOnce sync.Once
	file_atlantis_common_v1_interval_proto_rawDescData []byte
)

func file_atlantis_common_v1_interval_proto_rawDescGZIP() []byte {
	file_atlantis_common_v1_interval_proto_rawDescOnce.Do(func() {
		file_atlantis_common_v1_interval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_interval_proto_rawDesc), len(file_atlantis_common_v1_interval_proto_rawDesc)))
	})
	return file_atlantis_common_v1_interval_proto_rawDescData
}

var file_atlantis_common_v1_interval_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_atlantis_common_v1_interval_proto_goTypes = []any{
	(*Interval)(nil), // 0: atlantis.common.v1.Interval
}
var file_atlantis_common_v1_interval_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_atlantis_common_v1_interval_proto_init() }
func file_atlantis_common_v1_interval_proto_init() {
	if File_atlantis_common_v1_interval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_interval_proto_rawDesc), len(file_atlantis_common_v1_interval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atlantis_common_v1_interval_proto_goTypes,
		DependencyIndexes: file_atlantis_common_v1_interval_proto_depIdxs,
		MessageInfos:      file_atlantis_common_v1_interval_proto_msgTypes,
	}.Build()
	File_atlantis_common_v1_interval_proto = out.File
	file_atlantis_common_v1_interval_proto_goTypes = nil
	file_atlantis_common_v1_interval_proto_depIdxs = nil
}
