// PageToken is an opaque keyset cursor returned in QueryXResponse and
// echoed back unchanged. The embedded entity_id prevents using a
// cursor from one entity against another.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlantis/common/v1/pagination.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageToken carries the ORDER BY values + PK tiebreaker of the last
// row of a page. entity_id is "<namespace>.<EntityName>"; the decoder
// rejects cursors whose entity_id doesn't match the current request.
type PageToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Values        []*PageTokenValue      `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageToken) Reset() {
	*x = PageToken{}
	mi := &file_atlantis_common_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageToken) ProtoMessage() {}

func (x *PageToken) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageToken.ProtoReflect.Descriptor instead.
func (*PageToken) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PageToken) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PageToken) GetValues() []*PageTokenValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// One value per ORDER BY column plus PK tiebreaker. Numeric is sent
// as decimal string (gRPC has no arbitrary-precision decimal).
type PageTokenValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to V:
	//
	//	*PageTokenValue_S
	//	*PageTokenValue_I
	//	*PageTokenValue_B
	//	*PageTokenValue_Ts
	//	*PageTokenValue_Raw
	//	*PageTokenValue_Num
	//	*PageTokenValue_Null
	V             isPageTokenValue_V `protobuf_oneof:"v"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageTokenValue) Reset() {
	*x = PageTokenValue{}
	mi := &file_atlantis_common_v1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageTokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageTokenValue) ProtoMessage() {}

func (x *PageTokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageTokenValue.ProtoReflect.Descriptor instead.
func (*PageTokenValue) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PageTokenValue) GetV() isPageTokenValue_V {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *PageTokenValue) GetS() string {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *PageTokenValue) GetI() int64 {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *PageTokenValue) GetB() bool {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_B); ok {
			return x.B
		}
	}
	return false
}

func (x *PageTokenValue) GetTs() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_Ts); ok {
			return x.Ts
		}
	}
	return nil
}

func (x *PageTokenValue) GetRaw() []byte {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *PageTokenValue) GetNum() string {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_Num); ok {
			return x.Num
		}
	}
	return ""
}

func (x *PageTokenValue) GetNull() bool {
	if x != nil {
		if x, ok := x.V.(*PageTokenValue_Null); ok {
			return x.Null
		}
	}
	return false
}

type isPageTokenValue_V interface {
	isPageTokenValue_V()
}

type PageTokenValue_S struct {
	S string `protobuf:"bytes,1,opt,name=s,oneof"`
}

type PageTokenValue_I struct {
	I int64 `protobuf:"varint,2,opt,name=i,oneof"`
}

type PageTokenValue_B struct {
	B bool `protobuf:"varint,3,opt,name=b,oneof"`
}

type PageTokenValue_Ts struct {
	Ts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,oneof"`
}

type PageTokenValue_Raw struct {
	Raw []byte `protobuf:"bytes,5,opt,name=raw,oneof"`
}

type PageTokenValue_Num struct {
	Num string `protobuf:"bytes,6,opt,name=num,oneof"`
}

type PageTokenValue_Null struct {
	// A NULL ordering key.
	//
	// The ARM's presence is the whole signal; the bool carries nothing and
	// is always true. It cannot be expressed by omitting the value instead:
	// a PageToken holds one entry per ORDER BY column positionally, so a
	// missing entry would shift every later column onto the wrong one.
	//
	// A distinct arm is also what keeps NULL distinguishable from a real
	// zero. Before this existed, an unset optional scalar reached the cursor
	// as 0 or "" and the encoder could not tell the two apart, so a page
	// boundary landing on a NULL was written as a value that compares
	// in-range — which is how rows past it became unreachable.
	Null bool `protobuf:"varint,7,opt,name=null,oneof"`
}

func (*PageTokenValue_S) isPageTokenValue_V() {}

func (*PageTokenValue_I) isPageTokenValue_V() {}

func (*PageTokenValue_B) isPageTokenValue_V() {}

func (*PageTokenValue_Ts) isPageTokenValue_V() {}

func (*PageTokenValue_Raw) isPageTokenValue_V() {}

func (*PageTokenValue_Num) isPageTokenValue_V() {}

func (*PageTokenValue_Null) isPageTokenValue_V() {}

var File_atlantis_common_v1_pagination_proto protoreflect.FileDescriptor

const file_atlantis_common_v1_pagination_proto_rawDesc = "" +
	"\n" +
	"#atlantis/common/v1/pagination.proto\x12\x12atlantis.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\tPageToken\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12:\n" +
	"\x06values\x18\x02 \x03(\v2\".atlantis.common.v1.PageTokenValueR\x06values\"\xb1\x01\n" +
	"\x0ePageTokenValue\x12\x0e\n" +
	"\x01s\x18\x01 \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01i\x18\x02 \x01(\x03H\x00R\x01i\x12\x0e\n" +
	"\x01b\x18\x03 \x01(\bH\x00R\x01b\x12,\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x02ts\x12\x12\n" +
	"\x03raw\x18\x05 \x01(\fH\x00R\x03raw\x12\x12\n" +
	"\x03num\x18\x06 \x01(\tH\x00R\x03num\x12\x14\n" +
	"\x04null\x18\a \x01(\bH\x00R\x04nullB\x03\n" +
	"\x01vB\xf9\x01\n" +
	"\x16com.atlantis.common.v1B\x0fPaginationProtoP\x01Z_github.com/rachitkumar205/atlantis/internal/codegen/compilecheck/pb/atlantis/common/v1;commonv1\xa2\x02\x03ACX\xaa\x02\x12Atlantis.Common.V1\xca\x02\x12Atlantis\\Common\\V1\xe2\x02\x1eAtlantis\\Common\\V1\\GPBMetadata\xea\x02\x14Atlantis::Common::V1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_atlantis_common_v1_pagination_proto_rawDescOnce sync.Once
	file_atlantis_common_v1_pagination_proto_rawDescData []byte
)

func file_atlantis_common_v1_pagination_proto_rawDescGZIP() []byte {
	file_atlantis_common_v1_pagination_proto_rawDescOnce.Do(func() {
		file_atlantis_common_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_pagination_proto_rawDesc), len(file_atlantis_common_v1_pagination_proto_rawDesc)))
	})
	return file_atlantis_common_v1_pagination_proto_rawDescData
}

var file_atlantis_common_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_atlantis_common_v1_pagination_proto_goTypes = []any{
	(*PageToken)(nil),             // 0: atlantis.common.v1.PageToken
	(*PageTokenValue)(nil),        // 1: atlantis.common.v1.PageTokenValue
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_atlantis_common_v1_pagination_proto_depIdxs = []int32{
	1, // 0: atlantis.common.v1.PageToken.values:type_name -> atlantis.common.v1.PageTokenValue
	2, // 1: atlantis.common.v1.PageTokenValue.ts:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_atlantis_common_v1_pagination_proto_init() }
func file_atlantis_common_v1_pagination_proto_init() {
	if File_atlantis_common_v1_pagination_proto != nil {
		return
	}
	file_atlantis_common_v1_pagination_proto_msgTypes[1].OneofWrappers = []any{
		(*PageTokenValue_S)(nil),
		(*PageTokenValue_I)(nil),
		(*PageTokenValue_B)(nil),
		(*PageTokenValue_Ts)(nil),
		(*PageTokenValue_Raw)(nil),
		(*PageTokenValue_Num)(nil),
		(*PageTokenValue_Null)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_pagination_proto_rawDesc), len(file_atlantis_common_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atlantis_common_v1_pagination_proto_goTypes,
		DependencyIndexes: file_atlantis_common_v1_pagination_proto_depIdxs,
		MessageInfos:      file_atlantis_common_v1_pagination_proto_msgTypes,
	}.Build()
	File_atlantis_common_v1_pagination_proto = out.File
	file_atlantis_common_v1_pagination_proto_goTypes = nil
	file_atlantis_common_v1_pagination_proto_depIdxs = nil
}
