// Shared predicate messages. Entity codegen embeds these in QueryXFilter;
// the runtime translator (internal/codegen/query/translator.go) walks the
// set oneof arm to build the SQL fragment.
//
// New `op` arms must take the next free number; reuse a number only after
// the old arm has a 'reserved' line.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlantis/common/v1/predicates.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringPredicate covers text / varchar / citext / uuid. The LIKE-flavored
// arms (prefix/suffix/contains/ilike) escape `%` and `_` in caller input.
type StringPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*StringPredicate_Eq
	//	*StringPredicate_Neq
	//	*StringPredicate_In
	//	*StringPredicate_NotIn
	//	*StringPredicate_Prefix
	//	*StringPredicate_Suffix
	//	*StringPredicate_Contains
	//	*StringPredicate_Ilike
	//	*StringPredicate_IsNull
	//	*StringPredicate_IsNotNull
	Op            isStringPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPredicate) Reset() {
	*x = StringPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPredicate) ProtoMessage() {}

func (x *StringPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPredicate.ProtoReflect.Descriptor instead.
func (*StringPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{0}
}

func (x *StringPredicate) GetOp() isStringPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *StringPredicate) GetEq() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Eq); ok {
			return x.Eq
		}
	}
	return ""
}

func (x *StringPredicate) GetNeq() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Neq); ok {
			return x.Neq
		}
	}
	return ""
}

func (x *StringPredicate) GetIn() *StringList {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *StringPredicate) GetNotIn() *StringList {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_NotIn); ok {
			return x.NotIn
		}
	}
	return nil
}

func (x *StringPredicate) GetPrefix() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *StringPredicate) GetSuffix() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Suffix); ok {
			return x.Suffix
		}
	}
	return ""
}

func (x *StringPredicate) GetContains() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Contains); ok {
			return x.Contains
		}
	}
	return ""
}

func (x *StringPredicate) GetIlike() string {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_Ilike); ok {
			return x.Ilike
		}
	}
	return ""
}

func (x *StringPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *StringPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*StringPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isStringPredicate_Op interface {
	isStringPredicate_Op()
}

type StringPredicate_Eq struct {
	Eq string `protobuf:"bytes,1,opt,name=eq,oneof"`
}

type StringPredicate_Neq struct {
	Neq string `protobuf:"bytes,2,opt,name=neq,oneof"`
}

type StringPredicate_In struct {
	In *StringList `protobuf:"bytes,3,opt,name=in,oneof"`
}

type StringPredicate_NotIn struct {
	NotIn *StringList `protobuf:"bytes,4,opt,name=not_in,json=notIn,oneof"`
}

type StringPredicate_Prefix struct {
	Prefix string `protobuf:"bytes,5,opt,name=prefix,oneof"`
}

type StringPredicate_Suffix struct {
	Suffix string `protobuf:"bytes,6,opt,name=suffix,oneof"`
}

type StringPredicate_Contains struct {
	Contains string `protobuf:"bytes,7,opt,name=contains,oneof"`
}

type StringPredicate_Ilike struct {
	Ilike string `protobuf:"bytes,8,opt,name=ilike,oneof"`
}

type StringPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,9,opt,name=is_null,json=isNull,oneof"`
}

type StringPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,10,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*StringPredicate_Eq) isStringPredicate_Op() {}

func (*StringPredicate_Neq) isStringPredicate_Op() {}

func (*StringPredicate_In) isStringPredicate_Op() {}

func (*StringPredicate_NotIn) isStringPredicate_Op() {}

func (*StringPredicate_Prefix) isStringPredicate_Op() {}

func (*StringPredicate_Suffix) isStringPredicate_Op() {}

func (*StringPredicate_Contains) isStringPredicate_Op() {}

func (*StringPredicate_Ilike) isStringPredicate_Op() {}

func (*StringPredicate_IsNull) isStringPredicate_Op() {}

func (*StringPredicate_IsNotNull) isStringPredicate_Op() {}

// Int32Predicate handles smallint + int. `between` is inclusive;
// lo > hi is rejected (likely caller bug).
type Int32Predicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Int32Predicate_Eq
	//	*Int32Predicate_Neq
	//	*Int32Predicate_Lt
	//	*Int32Predicate_Lte
	//	*Int32Predicate_Gt
	//	*Int32Predicate_Gte
	//	*Int32Predicate_In
	//	*Int32Predicate_NotIn
	//	*Int32Predicate_Between
	//	*Int32Predicate_IsNull
	//	*Int32Predicate_IsNotNull
	Op            isInt32Predicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Predicate) Reset() {
	*x = Int32Predicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Predicate) ProtoMessage() {}

func (x *Int32Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Predicate.ProtoReflect.Descriptor instead.
func (*Int32Predicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{1}
}

func (x *Int32Predicate) GetOp() isInt32Predicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Int32Predicate) GetEq() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Eq); ok {
			return x.Eq
		}
	}
	return 0
}

func (x *Int32Predicate) GetNeq() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Neq); ok {
			return x.Neq
		}
	}
	return 0
}

func (x *Int32Predicate) GetLt() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Lt); ok {
			return x.Lt
		}
	}
	return 0
}

func (x *Int32Predicate) GetLte() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Lte); ok {
			return x.Lte
		}
	}
	return 0
}

func (x *Int32Predicate) GetGt() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Gt); ok {
			return x.Gt
		}
	}
	return 0
}

func (x *Int32Predicate) GetGte() int32 {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Gte); ok {
			return x.Gte
		}
	}
	return 0
}

func (x *Int32Predicate) GetIn() *Int32List {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *Int32Predicate) GetNotIn() *Int32List {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_NotIn); ok {
			return x.NotIn
		}
	}
	return nil
}

func (x *Int32Predicate) GetBetween() *Int32Range {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_Between); ok {
			return x.Between
		}
	}
	return nil
}

func (x *Int32Predicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *Int32Predicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*Int32Predicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isInt32Predicate_Op interface {
	isInt32Predicate_Op()
}

type Int32Predicate_Eq struct {
	Eq int32 `protobuf:"varint,1,opt,name=eq,oneof"`
}

type Int32Predicate_Neq struct {
	Neq int32 `protobuf:"varint,2,opt,name=neq,oneof"`
}

type Int32Predicate_Lt struct {
	Lt int32 `protobuf:"varint,3,opt,name=lt,oneof"`
}

type Int32Predicate_Lte struct {
	Lte int32 `protobuf:"varint,4,opt,name=lte,oneof"`
}

type Int32Predicate_Gt struct {
	Gt int32 `protobuf:"varint,5,opt,name=gt,oneof"`
}

type Int32Predicate_Gte struct {
	Gte int32 `protobuf:"varint,6,opt,name=gte,oneof"`
}

type Int32Predicate_In struct {
	In *Int32List `protobuf:"bytes,7,opt,name=in,oneof"`
}

type Int32Predicate_NotIn struct {
	NotIn *Int32List `protobuf:"bytes,8,opt,name=not_in,json=notIn,oneof"`
}

type Int32Predicate_Between struct {
	Between *Int32Range `protobuf:"bytes,9,opt,name=between,oneof"`
}

type Int32Predicate_IsNull struct {
	IsNull bool `protobuf:"varint,10,opt,name=is_null,json=isNull,oneof"`
}

type Int32Predicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,11,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*Int32Predicate_Eq) isInt32Predicate_Op() {}

func (*Int32Predicate_Neq) isInt32Predicate_Op() {}

func (*Int32Predicate_Lt) isInt32Predicate_Op() {}

func (*Int32Predicate_Lte) isInt32Predicate_Op() {}

func (*Int32Predicate_Gt) isInt32Predicate_Op() {}

func (*Int32Predicate_Gte) isInt32Predicate_Op() {}

func (*Int32Predicate_In) isInt32Predicate_Op() {}

func (*Int32Predicate_NotIn) isInt32Predicate_Op() {}

func (*Int32Predicate_Between) isInt32Predicate_Op() {}

func (*Int32Predicate_IsNull) isInt32Predicate_Op() {}

func (*Int32Predicate_IsNotNull) isInt32Predicate_Op() {}

type Int64Predicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Int64Predicate_Eq
	//	*Int64Predicate_Neq
	//	*Int64Predicate_Lt
	//	*Int64Predicate_Lte
	//	*Int64Predicate_Gt
	//	*Int64Predicate_Gte
	//	*Int64Predicate_In
	//	*Int64Predicate_NotIn
	//	*Int64Predicate_Between
	//	*Int64Predicate_IsNull
	//	*Int64Predicate_IsNotNull
	Op            isInt64Predicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Predicate) Reset() {
	*x = Int64Predicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Predicate) ProtoMessage() {}

func (x *Int64Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Predicate.ProtoReflect.Descriptor instead.
func (*Int64Predicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{2}
}

func (x *Int64Predicate) GetOp() isInt64Predicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Int64Predicate) GetEq() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Eq); ok {
			return x.Eq
		}
	}
	return 0
}

func (x *Int64Predicate) GetNeq() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Neq); ok {
			return x.Neq
		}
	}
	return 0
}

func (x *Int64Predicate) GetLt() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Lt); ok {
			return x.Lt
		}
	}
	return 0
}

func (x *Int64Predicate) GetLte() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Lte); ok {
			return x.Lte
		}
	}
	return 0
}

func (x *Int64Predicate) GetGt() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Gt); ok {
			return x.Gt
		}
	}
	return 0
}

func (x *Int64Predicate) GetGte() int64 {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Gte); ok {
			return x.Gte
		}
	}
	return 0
}

func (x *Int64Predicate) GetIn() *Int64List {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *Int64Predicate) GetNotIn() *Int64List {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_NotIn); ok {
			return x.NotIn
		}
	}
	return nil
}

func (x *Int64Predicate) GetBetween() *Int64Range {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_Between); ok {
			return x.Between
		}
	}
	return nil
}

func (x *Int64Predicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *Int64Predicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*Int64Predicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isInt64Predicate_Op interface {
	isInt64Predicate_Op()
}

type Int64Predicate_Eq struct {
	Eq int64 `protobuf:"varint,1,opt,name=eq,oneof"`
}

type Int64Predicate_Neq struct {
	Neq int64 `protobuf:"varint,2,opt,name=neq,oneof"`
}

type Int64Predicate_Lt struct {
	Lt int64 `protobuf:"varint,3,opt,name=lt,oneof"`
}

type Int64Predicate_Lte struct {
	Lte int64 `protobuf:"varint,4,opt,name=lte,oneof"`
}

type Int64Predicate_Gt struct {
	Gt int64 `protobuf:"varint,5,opt,name=gt,oneof"`
}

type Int64Predicate_Gte struct {
	Gte int64 `protobuf:"varint,6,opt,name=gte,oneof"`
}

type Int64Predicate_In struct {
	In *Int64List `protobuf:"bytes,7,opt,name=in,oneof"`
}

type Int64Predicate_NotIn struct {
	NotIn *Int64List `protobuf:"bytes,8,opt,name=not_in,json=notIn,oneof"`
}

type Int64Predicate_Between struct {
	Between *Int64Range `protobuf:"bytes,9,opt,name=between,oneof"`
}

type Int64Predicate_IsNull struct {
	IsNull bool `protobuf:"varint,10,opt,name=is_null,json=isNull,oneof"`
}

type Int64Predicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,11,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*Int64Predicate_Eq) isInt64Predicate_Op() {}

func (*Int64Predicate_Neq) isInt64Predicate_Op() {}

func (*Int64Predicate_Lt) isInt64Predicate_Op() {}

func (*Int64Predicate_Lte) isInt64Predicate_Op() {}

func (*Int64Predicate_Gt) isInt64Predicate_Op() {}

func (*Int64Predicate_Gte) isInt64Predicate_Op() {}

func (*Int64Predicate_In) isInt64Predicate_Op() {}

func (*Int64Predicate_NotIn) isInt64Predicate_Op() {}

func (*Int64Predicate_Between) isInt64Predicate_Op() {}

func (*Int64Predicate_IsNull) isInt64Predicate_Op() {}

func (*Int64Predicate_IsNotNull) isInt64Predicate_Op() {}

type BoolPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*BoolPredicate_Eq
	//	*BoolPredicate_IsNull
	//	*BoolPredicate_IsNotNull
	Op            isBoolPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolPredicate) Reset() {
	*x = BoolPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolPredicate) ProtoMessage() {}

func (x *BoolPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolPredicate.ProtoReflect.Descriptor instead.
func (*BoolPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{3}
}

func (x *BoolPredicate) GetOp() isBoolPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *BoolPredicate) GetEq() bool {
	if x != nil {
		if x, ok := x.Op.(*BoolPredicate_Eq); ok {
			return x.Eq
		}
	}
	return false
}

func (x *BoolPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*BoolPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *BoolPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*BoolPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isBoolPredicate_Op interface {
	isBoolPredicate_Op()
}

type BoolPredicate_Eq struct {
	Eq bool `protobuf:"varint,1,opt,name=eq,oneof"`
}

type BoolPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,2,opt,name=is_null,json=isNull,oneof"`
}

type BoolPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,3,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*BoolPredicate_Eq) isBoolPredicate_Op() {}

func (*BoolPredicate_IsNull) isBoolPredicate_Op() {}

func (*BoolPredicate_IsNotNull) isBoolPredicate_Op() {}

// TimestampPredicate uses google.protobuf.Timestamp. `between` is inclusive.
// Out-of-range timestamps are rejected by the proto codec.
type TimestampPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*TimestampPredicate_Eq
	//	*TimestampPredicate_Neq
	//	*TimestampPredicate_Lt
	//	*TimestampPredicate_Lte
	//	*TimestampPredicate_Gt
	//	*TimestampPredicate_Gte
	//	*TimestampPredicate_Between
	//	*TimestampPredicate_IsNull
	//	*TimestampPredicate_IsNotNull
	Op            isTimestampPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampPredicate) Reset() {
	*x = TimestampPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampPredicate) ProtoMessage() {}

func (x *TimestampPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampPredicate.ProtoReflect.Descriptor instead.
func (*TimestampPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{4}
}

func (x *TimestampPredicate) GetOp() isTimestampPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *TimestampPredicate) GetEq() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *TimestampPredicate) GetNeq() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Neq); ok {
			return x.Neq
		}
	}
	return nil
}

func (x *TimestampPredicate) GetLt() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Lt); ok {
			return x.Lt
		}
	}
	return nil
}

func (x *TimestampPredicate) GetLte() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Lte); ok {
			return x.Lte
		}
	}
	return nil
}

func (x *TimestampPredicate) GetGt() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Gt); ok {
			return x.Gt
		}
	}
	return nil
}

func (x *TimestampPredicate) GetGte() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Gte); ok {
			return x.Gte
		}
	}
	return nil
}

func (x *TimestampPredicate) GetBetween() *TimestampRange {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_Between); ok {
			return x.Between
		}
	}
	return nil
}

func (x *TimestampPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *TimestampPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*TimestampPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isTimestampPredicate_Op interface {
	isTimestampPredicate_Op()
}

type TimestampPredicate_Eq struct {
	Eq *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=eq,oneof"`
}

type TimestampPredicate_Neq struct {
	Neq *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=neq,oneof"`
}

type TimestampPredicate_Lt struct {
	Lt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lt,oneof"`
}

type TimestampPredicate_Lte struct {
	Lte *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lte,oneof"`
}

type TimestampPredicate_Gt struct {
	Gt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=gt,oneof"`
}

type TimestampPredicate_Gte struct {
	Gte *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=gte,oneof"`
}

type TimestampPredicate_Between struct {
	Between *TimestampRange `protobuf:"bytes,7,opt,name=between,oneof"`
}

type TimestampPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,8,opt,name=is_null,json=isNull,oneof"`
}

type TimestampPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,9,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*TimestampPredicate_Eq) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Neq) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Lt) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Lte) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Gt) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Gte) isTimestampPredicate_Op() {}

func (*TimestampPredicate_Between) isTimestampPredicate_Op() {}

func (*TimestampPredicate_IsNull) isTimestampPredicate_Op() {}

func (*TimestampPredicate_IsNotNull) isTimestampPredicate_Op() {}

// BytesPredicate covers bytea and (for now) jsonb. JSONB equality is
// byte-for-byte against PG's normalized rendering; value-level JSON
// predicates are not supported yet.
type BytesPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*BytesPredicate_Eq
	//	*BytesPredicate_Neq
	//	*BytesPredicate_In
	//	*BytesPredicate_IsNull
	//	*BytesPredicate_IsNotNull
	Op            isBytesPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesPredicate) Reset() {
	*x = BytesPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesPredicate) ProtoMessage() {}

func (x *BytesPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesPredicate.ProtoReflect.Descriptor instead.
func (*BytesPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{5}
}

func (x *BytesPredicate) GetOp() isBytesPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *BytesPredicate) GetEq() []byte {
	if x != nil {
		if x, ok := x.Op.(*BytesPredicate_Eq); ok {
			return x.Eq
		}
	}
	return nil
}

func (x *BytesPredicate) GetNeq() []byte {
	if x != nil {
		if x, ok := x.Op.(*BytesPredicate_Neq); ok {
			return x.Neq
		}
	}
	return nil
}

func (x *BytesPredicate) GetIn() *BytesList {
	if x != nil {
		if x, ok := x.Op.(*BytesPredicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *BytesPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*BytesPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *BytesPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*BytesPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isBytesPredicate_Op interface {
	isBytesPredicate_Op()
}

type BytesPredicate_Eq struct {
	Eq []byte `protobuf:"bytes,1,opt,name=eq,oneof"`
}

type BytesPredicate_Neq struct {
	Neq []byte `protobuf:"bytes,2,opt,name=neq,oneof"`
}

type BytesPredicate_In struct {
	In *BytesList `protobuf:"bytes,3,opt,name=in,oneof"`
}

type BytesPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,4,opt,name=is_null,json=isNull,oneof"`
}

type BytesPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,5,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*BytesPredicate_Eq) isBytesPredicate_Op() {}

func (*BytesPredicate_Neq) isBytesPredicate_Op() {}

func (*BytesPredicate_In) isBytesPredicate_Op() {}

func (*BytesPredicate_IsNull) isBytesPredicate_Op() {}

func (*BytesPredicate_IsNotNull) isBytesPredicate_Op() {}

// NumericPredicate carries numeric/decimal columns as decimal strings;
// the translator casts to PG numeric on both sides of the comparison.
type NumericPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*NumericPredicate_Eq
	//	*NumericPredicate_Neq
	//	*NumericPredicate_Lt
	//	*NumericPredicate_Lte
	//	*NumericPredicate_Gt
	//	*NumericPredicate_Gte
	//	*NumericPredicate_In
	//	*NumericPredicate_IsNull
	//	*NumericPredicate_IsNotNull
	Op            isNumericPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericPredicate) Reset() {
	*x = NumericPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericPredicate) ProtoMessage() {}

func (x *NumericPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericPredicate.ProtoReflect.Descriptor instead.
func (*NumericPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{6}
}

func (x *NumericPredicate) GetOp() isNumericPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *NumericPredicate) GetEq() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Eq); ok {
			return x.Eq
		}
	}
	return ""
}

func (x *NumericPredicate) GetNeq() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Neq); ok {
			return x.Neq
		}
	}
	return ""
}

func (x *NumericPredicate) GetLt() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Lt); ok {
			return x.Lt
		}
	}
	return ""
}

func (x *NumericPredicate) GetLte() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Lte); ok {
			return x.Lte
		}
	}
	return ""
}

func (x *NumericPredicate) GetGt() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Gt); ok {
			return x.Gt
		}
	}
	return ""
}

func (x *NumericPredicate) GetGte() string {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_Gte); ok {
			return x.Gte
		}
	}
	return ""
}

func (x *NumericPredicate) GetIn() *StringList {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *NumericPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *NumericPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*NumericPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isNumericPredicate_Op interface {
	isNumericPredicate_Op()
}

type NumericPredicate_Eq struct {
	Eq string `protobuf:"bytes,1,opt,name=eq,oneof"`
}

type NumericPredicate_Neq struct {
	Neq string `protobuf:"bytes,2,opt,name=neq,oneof"`
}

type NumericPredicate_Lt struct {
	Lt string `protobuf:"bytes,3,opt,name=lt,oneof"`
}

type NumericPredicate_Lte struct {
	Lte string `protobuf:"bytes,4,opt,name=lte,oneof"`
}

type NumericPredicate_Gt struct {
	Gt string `protobuf:"bytes,5,opt,name=gt,oneof"`
}

type NumericPredicate_Gte struct {
	Gte string `protobuf:"bytes,6,opt,name=gte,oneof"`
}

type NumericPredicate_In struct {
	In *StringList `protobuf:"bytes,7,opt,name=in,oneof"`
}

type NumericPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,8,opt,name=is_null,json=isNull,oneof"`
}

type NumericPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,9,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*NumericPredicate_Eq) isNumericPredicate_Op() {}

func (*NumericPredicate_Neq) isNumericPredicate_Op() {}

func (*NumericPredicate_Lt) isNumericPredicate_Op() {}

func (*NumericPredicate_Lte) isNumericPredicate_Op() {}

func (*NumericPredicate_Gt) isNumericPredicate_Op() {}

func (*NumericPredicate_Gte) isNumericPredicate_Op() {}

func (*NumericPredicate_In) isNumericPredicate_Op() {}

func (*NumericPredicate_IsNull) isNumericPredicate_Op() {}

func (*NumericPredicate_IsNotNull) isNumericPredicate_Op() {}

// FloatPredicate covers `real` (PG float4); DoublePredicate covers `double`
// (float8). Two messages rather than one, and the arm width is the point.
//
// # Why the widths are kept apart
//
// float8 is a strict superset of float4, so a single double-carrying message
// would be expressive enough. It would also sit on the wrong side of a real
// hazard: PG promotes a float4 column to float8 to compare it against a float8
// value, and a row storing 0.1 in a `real` column promotes to
// 0.10000000149011612. `WHERE score = 0.1::float8` therefore returns nothing
// while the value plainly reads back as 0.1 — measured, not reasoned.
//
// Carrying the caller's value at the column's own width keeps the comparison
// inside float4. The SQL side casts the placeholder to match (see
// translateFloatPredicate), and pgx independently negotiates the parameter type
// with PG, so today all three agree and any one would do. The width being
// stated in the message is the half a CALLER can see: a client library reading
// this proto binds a float32 for a float4 column without having to know what
// the server does with it.
//
// # What this does NOT fix
//
// Float equality is still float equality. `eq` on a value that was computed
// rather than round-tripped from the same literal can miss, on either width.
// The arms exist because a caller who knows their data expects them, not
// because they are safe in general.
//
// # Ordering is float8, deliberately
//
// ORDER BY and the keyset cursor compare a `real` column after promotion to
// float8, because the page token carries the promoted value (see
// runtime.EncodePageToken). Filtering therefore compares at float4 and ordering
// at float8. For `double` the two coincide; for `real` they can disagree at the
// boundary, and a PG test pins that a filtered page still returns every matching
// row exactly once.
type FloatPredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*FloatPredicate_Eq
	//	*FloatPredicate_Neq
	//	*FloatPredicate_Lt
	//	*FloatPredicate_Lte
	//	*FloatPredicate_Gt
	//	*FloatPredicate_Gte
	//	*FloatPredicate_In
	//	*FloatPredicate_IsNull
	//	*FloatPredicate_IsNotNull
	Op            isFloatPredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatPredicate) Reset() {
	*x = FloatPredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatPredicate) ProtoMessage() {}

func (x *FloatPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatPredicate.ProtoReflect.Descriptor instead.
func (*FloatPredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{7}
}

func (x *FloatPredicate) GetOp() isFloatPredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *FloatPredicate) GetEq() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Eq); ok {
			return x.Eq
		}
	}
	return 0
}

func (x *FloatPredicate) GetNeq() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Neq); ok {
			return x.Neq
		}
	}
	return 0
}

func (x *FloatPredicate) GetLt() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Lt); ok {
			return x.Lt
		}
	}
	return 0
}

func (x *FloatPredicate) GetLte() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Lte); ok {
			return x.Lte
		}
	}
	return 0
}

func (x *FloatPredicate) GetGt() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Gt); ok {
			return x.Gt
		}
	}
	return 0
}

func (x *FloatPredicate) GetGte() float32 {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_Gte); ok {
			return x.Gte
		}
	}
	return 0
}

func (x *FloatPredicate) GetIn() *FloatList {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *FloatPredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *FloatPredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*FloatPredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isFloatPredicate_Op interface {
	isFloatPredicate_Op()
}

type FloatPredicate_Eq struct {
	Eq float32 `protobuf:"fixed32,1,opt,name=eq,oneof"`
}

type FloatPredicate_Neq struct {
	Neq float32 `protobuf:"fixed32,2,opt,name=neq,oneof"`
}

type FloatPredicate_Lt struct {
	Lt float32 `protobuf:"fixed32,3,opt,name=lt,oneof"`
}

type FloatPredicate_Lte struct {
	Lte float32 `protobuf:"fixed32,4,opt,name=lte,oneof"`
}

type FloatPredicate_Gt struct {
	Gt float32 `protobuf:"fixed32,5,opt,name=gt,oneof"`
}

type FloatPredicate_Gte struct {
	Gte float32 `protobuf:"fixed32,6,opt,name=gte,oneof"`
}

type FloatPredicate_In struct {
	In *FloatList `protobuf:"bytes,7,opt,name=in,oneof"`
}

type FloatPredicate_IsNull struct {
	IsNull bool `protobuf:"varint,8,opt,name=is_null,json=isNull,oneof"`
}

type FloatPredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,9,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*FloatPredicate_Eq) isFloatPredicate_Op() {}

func (*FloatPredicate_Neq) isFloatPredicate_Op() {}

func (*FloatPredicate_Lt) isFloatPredicate_Op() {}

func (*FloatPredicate_Lte) isFloatPredicate_Op() {}

func (*FloatPredicate_Gt) isFloatPredicate_Op() {}

func (*FloatPredicate_Gte) isFloatPredicate_Op() {}

func (*FloatPredicate_In) isFloatPredicate_Op() {}

func (*FloatPredicate_IsNull) isFloatPredicate_Op() {}

func (*FloatPredicate_IsNotNull) isFloatPredicate_Op() {}

type DoublePredicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*DoublePredicate_Eq
	//	*DoublePredicate_Neq
	//	*DoublePredicate_Lt
	//	*DoublePredicate_Lte
	//	*DoublePredicate_Gt
	//	*DoublePredicate_Gte
	//	*DoublePredicate_In
	//	*DoublePredicate_IsNull
	//	*DoublePredicate_IsNotNull
	Op            isDoublePredicate_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoublePredicate) Reset() {
	*x = DoublePredicate{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoublePredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoublePredicate) ProtoMessage() {}

func (x *DoublePredicate) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoublePredicate.ProtoReflect.Descriptor instead.
func (*DoublePredicate) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{8}
}

func (x *DoublePredicate) GetOp() isDoublePredicate_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *DoublePredicate) GetEq() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Eq); ok {
			return x.Eq
		}
	}
	return 0
}

func (x *DoublePredicate) GetNeq() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Neq); ok {
			return x.Neq
		}
	}
	return 0
}

func (x *DoublePredicate) GetLt() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Lt); ok {
			return x.Lt
		}
	}
	return 0
}

func (x *DoublePredicate) GetLte() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Lte); ok {
			return x.Lte
		}
	}
	return 0
}

func (x *DoublePredicate) GetGt() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Gt); ok {
			return x.Gt
		}
	}
	return 0
}

func (x *DoublePredicate) GetGte() float64 {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_Gte); ok {
			return x.Gte
		}
	}
	return 0
}

func (x *DoublePredicate) GetIn() *DoubleList {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_In); ok {
			return x.In
		}
	}
	return nil
}

func (x *DoublePredicate) GetIsNull() bool {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_IsNull); ok {
			return x.IsNull
		}
	}
	return false
}

func (x *DoublePredicate) GetIsNotNull() bool {
	if x != nil {
		if x, ok := x.Op.(*DoublePredicate_IsNotNull); ok {
			return x.IsNotNull
		}
	}
	return false
}

type isDoublePredicate_Op interface {
	isDoublePredicate_Op()
}

type DoublePredicate_Eq struct {
	Eq float64 `protobuf:"fixed64,1,opt,name=eq,oneof"`
}

type DoublePredicate_Neq struct {
	Neq float64 `protobuf:"fixed64,2,opt,name=neq,oneof"`
}

type DoublePredicate_Lt struct {
	Lt float64 `protobuf:"fixed64,3,opt,name=lt,oneof"`
}

type DoublePredicate_Lte struct {
	Lte float64 `protobuf:"fixed64,4,opt,name=lte,oneof"`
}

type DoublePredicate_Gt struct {
	Gt float64 `protobuf:"fixed64,5,opt,name=gt,oneof"`
}

type DoublePredicate_Gte struct {
	Gte float64 `protobuf:"fixed64,6,opt,name=gte,oneof"`
}

type DoublePredicate_In struct {
	In *DoubleList `protobuf:"bytes,7,opt,name=in,oneof"`
}

type DoublePredicate_IsNull struct {
	IsNull bool `protobuf:"varint,8,opt,name=is_null,json=isNull,oneof"`
}

type DoublePredicate_IsNotNull struct {
	IsNotNull bool `protobuf:"varint,9,opt,name=is_not_null,json=isNotNull,oneof"`
}

func (*DoublePredicate_Eq) isDoublePredicate_Op() {}

func (*DoublePredicate_Neq) isDoublePredicate_Op() {}

func (*DoublePredicate_Lt) isDoublePredicate_Op() {}

func (*DoublePredicate_Lte) isDoublePredicate_Op() {}

func (*DoublePredicate_Gt) isDoublePredicate_Op() {}

func (*DoublePredicate_Gte) isDoublePredicate_Op() {}

func (*DoublePredicate_In) isDoublePredicate_Op() {}

func (*DoublePredicate_IsNull) isDoublePredicate_Op() {}

func (*DoublePredicate_IsNotNull) isDoublePredicate_Op() {}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{9}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32List) Reset() {
	*x = Int32List{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32List) ProtoMessage() {}

func (x *Int32List) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32List.ProtoReflect.Descriptor instead.
func (*Int32List) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{10}
}

func (x *Int32List) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int64List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64List) Reset() {
	*x = Int64List{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64List) ProtoMessage() {}

func (x *Int64List) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64List.ProtoReflect.Descriptor instead.
func (*Int64List) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{11}
}

func (x *Int64List) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BytesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesList) Reset() {
	*x = BytesList{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesList) ProtoMessage() {}

func (x *BytesList) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesList.ProtoReflect.Descriptor instead.
func (*BytesList) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{12}
}

func (x *BytesList) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatList) Reset() {
	*x = FloatList{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatList) ProtoMessage() {}

func (x *FloatList) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatList.ProtoReflect.Descriptor instead.
func (*FloatList) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{13}
}

func (x *FloatList) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type DoubleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleList) Reset() {
	*x = DoubleList{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleList) ProtoMessage() {}

func (x *DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleList.ProtoReflect.Descriptor instead.
func (*DoubleList) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{14}
}

func (x *DoubleList) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int32Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            int32                  `protobuf:"varint,1,opt,name=lo" json:"lo,omitempty"`
	Hi            int32                  `protobuf:"varint,2,opt,name=hi" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Range) Reset() {
	*x = Int32Range{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Range) ProtoMessage() {}

func (x *Int32Range) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Range.ProtoReflect.Descriptor instead.
func (*Int32Range) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{15}
}

func (x *Int32Range) GetLo() int32 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Int32Range) GetHi() int32 {
	if x != nil {
		return x.Hi
	}
	return 0
}

type Int64Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            int64                  `protobuf:"varint,1,opt,name=lo" json:"lo,omitempty"`
	Hi            int64                  `protobuf:"varint,2,opt,name=hi" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Range) Reset() {
	*x = Int64Range{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Range) ProtoMessage() {}

func (x *Int64Range) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Range.ProtoReflect.Descriptor instead.
func (*Int64Range) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{16}
}

func (x *Int64Range) GetLo() int64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *Int64Range) GetHi() int64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

type TimestampRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=lo" json:"lo,omitempty"`
	Hi            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=hi" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampRange) Reset() {
	*x = TimestampRange{}
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampRange) ProtoMessage() {}

func (x *TimestampRange) ProtoReflect() protoreflect.Message {
	mi := &file_atlantis_common_v1_predicates_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampRange.ProtoReflect.Descriptor instead.
func (*TimestampRange) Descriptor() ([]byte, []int) {
	return file_atlantis_common_v1_predicates_proto_rawDescGZIP(), []int{17}
}

func (x *TimestampRange) GetLo() *timestamppb.Timestamp {
	if x != nil {
		return x.Lo
	}
	return nil
}

func (x *TimestampRange) GetHi() *timestamppb.Timestamp {
	if x != nil {
		return x.Hi
	}
	return nil
}

var File_atlantis_common_v1_predicates_proto protoreflect.FileDescriptor

const file_atlantis_common_v1_predicates_proto_rawDesc = "" +
	"\n" +
	"#atlantis/common/v1/predicates.proto\x12\x12atlantis.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\x0fStringPredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\tH\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\tH\x00R\x03neq\x120\n" +
	"\x02in\x18\x03 \x01(\v2\x1e.atlantis.common.v1.StringListH\x00R\x02in\x127\n" +
	"\x06not_in\x18\x04 \x01(\v2\x1e.atlantis.common.v1.StringListH\x00R\x05notIn\x12\x18\n" +
	"\x06prefix\x18\x05 \x01(\tH\x00R\x06prefix\x12\x18\n" +
	"\x06suffix\x18\x06 \x01(\tH\x00R\x06suffix\x12\x1c\n" +
	"\bcontains\x18\a \x01(\tH\x00R\bcontains\x12\x16\n" +
	"\x05ilike\x18\b \x01(\tH\x00R\x05ilike\x12\x19\n" +
	"\ais_null\x18\t \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\n" +
	" \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xea\x02\n" +
	"\x0eInt32Predicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\x05H\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\x05H\x00R\x03neq\x12\x10\n" +
	"\x02lt\x18\x03 \x01(\x05H\x00R\x02lt\x12\x12\n" +
	"\x03lte\x18\x04 \x01(\x05H\x00R\x03lte\x12\x10\n" +
	"\x02gt\x18\x05 \x01(\x05H\x00R\x02gt\x12\x12\n" +
	"\x03gte\x18\x06 \x01(\x05H\x00R\x03gte\x12/\n" +
	"\x02in\x18\a \x01(\v2\x1d.atlantis.common.v1.Int32ListH\x00R\x02in\x126\n" +
	"\x06not_in\x18\b \x01(\v2\x1d.atlantis.common.v1.Int32ListH\x00R\x05notIn\x12:\n" +
	"\abetween\x18\t \x01(\v2\x1e.atlantis.common.v1.Int32RangeH\x00R\abetween\x12\x19\n" +
	"\ais_null\x18\n" +
	" \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\v \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xea\x02\n" +
	"\x0eInt64Predicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\x03H\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\x03H\x00R\x03neq\x12\x10\n" +
	"\x02lt\x18\x03 \x01(\x03H\x00R\x02lt\x12\x12\n" +
	"\x03lte\x18\x04 \x01(\x03H\x00R\x03lte\x12\x10\n" +
	"\x02gt\x18\x05 \x01(\x03H\x00R\x02gt\x12\x12\n" +
	"\x03gte\x18\x06 \x01(\x03H\x00R\x03gte\x12/\n" +
	"\x02in\x18\a \x01(\v2\x1d.atlantis.common.v1.Int64ListH\x00R\x02in\x126\n" +
	"\x06not_in\x18\b \x01(\v2\x1d.atlantis.common.v1.Int64ListH\x00R\x05notIn\x12:\n" +
	"\abetween\x18\t \x01(\v2\x1e.atlantis.common.v1.Int64RangeH\x00R\abetween\x12\x19\n" +
	"\ais_null\x18\n" +
	" \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\v \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"d\n" +
	"\rBoolPredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\bH\x00R\x02eq\x12\x19\n" +
	"\ais_null\x18\x02 \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\x03 \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xb1\x03\n" +
	"\x12TimestampPredicate\x12,\n" +
	"\x02eq\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x02eq\x12.\n" +
	"\x03neq\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x03neq\x12,\n" +
	"\x02lt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x02lt\x12.\n" +
	"\x03lte\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x03lte\x12,\n" +
	"\x02gt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x02gt\x12.\n" +
	"\x03gte\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x03gte\x12>\n" +
	"\abetween\x18\a \x01(\v2\".atlantis.common.v1.TimestampRangeH\x00R\abetween\x12\x19\n" +
	"\ais_null\x18\b \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\t \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xaa\x01\n" +
	"\x0eBytesPredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\fH\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\fH\x00R\x03neq\x12/\n" +
	"\x02in\x18\x03 \x01(\v2\x1d.atlantis.common.v1.BytesListH\x00R\x02in\x12\x19\n" +
	"\ais_null\x18\x04 \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\x05 \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xf9\x01\n" +
	"\x10NumericPredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\tH\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\tH\x00R\x03neq\x12\x10\n" +
	"\x02lt\x18\x03 \x01(\tH\x00R\x02lt\x12\x12\n" +
	"\x03lte\x18\x04 \x01(\tH\x00R\x03lte\x12\x10\n" +
	"\x02gt\x18\x05 \x01(\tH\x00R\x02gt\x12\x12\n" +
	"\x03gte\x18\x06 \x01(\tH\x00R\x03gte\x120\n" +
	"\x02in\x18\a \x01(\v2\x1e.atlantis.common.v1.StringListH\x00R\x02in\x12\x19\n" +
	"\ais_null\x18\b \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\t \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xf6\x01\n" +
	"\x0eFloatPredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\x02H\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\x02H\x00R\x03neq\x12\x10\n" +
	"\x02lt\x18\x03 \x01(\x02H\x00R\x02lt\x12\x12\n" +
	"\x03lte\x18\x04 \x01(\x02H\x00R\x03lte\x12\x10\n" +
	"\x02gt\x18\x05 \x01(\x02H\x00R\x02gt\x12\x12\n" +
	"\x03gte\x18\x06 \x01(\x02H\x00R\x03gte\x12/\n" +
	"\x02in\x18\a \x01(\v2\x1d.atlantis.common.v1.FloatListH\x00R\x02in\x12\x19\n" +
	"\ais_null\x18\b \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\t \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"\xf8\x01\n" +
	"\x0fDoublePredicate\x12\x10\n" +
	"\x02eq\x18\x01 \x01(\x01H\x00R\x02eq\x12\x12\n" +
	"\x03neq\x18\x02 \x01(\x01H\x00R\x03neq\x12\x10\n" +
	"\x02lt\x18\x03 \x01(\x01H\x00R\x02lt\x12\x12\n" +
	"\x03lte\x18\x04 \x01(\x01H\x00R\x03lte\x12\x10\n" +
	"\x02gt\x18\x05 \x01(\x01H\x00R\x02gt\x12\x12\n" +
	"\x03gte\x18\x06 \x01(\x01H\x00R\x03gte\x120\n" +
	"\x02in\x18\a \x01(\v2\x1e.atlantis.common.v1.DoubleListH\x00R\x02in\x12\x19\n" +
	"\ais_null\x18\b \x01(\bH\x00R\x06isNull\x12 \n" +
	"\vis_not_null\x18\t \x01(\bH\x00R\tisNotNullB\x04\n" +
	"\x02op\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"#\n" +
	"\tInt32List\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"#\n" +
	"\tInt64List\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"#\n" +
	"\tBytesList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"#\n" +
	"\tFloatList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"$\n" +
	"\n" +
	"DoubleList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\",\n" +
	"\n" +
	"Int32Range\x12\x0e\n" +
	"\x02lo\x18\x01 \x01(\x05R\x02lo\x12\x0e\n" +
	"\x02hi\x18\x02 \x01(\x05R\x02hi\",\n" +
	"\n" +
	"Int64Range\x12\x0e\n" +
	"\x02lo\x18\x01 \x01(\x03R\x02lo\x12\x0e\n" +
	"\x02hi\x18\x02 \x01(\x03R\x02hi\"h\n" +
	"\x0eTimestampRange\x12*\n" +
	"\x02lo\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02lo\x12*\n" +
	"\x02hi\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02hiB\xf9\x01\n" +
	"\x16com.atlantis.common.v1B\x0fPredicatesProtoP\x01Z_github.com/rachitkumar205/atlantis/internal/codegen/compilecheck/pb/atlantis/common/v1;commonv1\xa2\x02\x03ACX\xaa\x02\x12Atlantis.Common.V1\xca\x02\x12Atlantis\\Common\\V1\xe2\x02\x1eAtlantis\\Common\\V1\\GPBMetadata\xea\x02\x14Atlantis::Common::V1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_atlantis_common_v1_predicates_proto_rawDescOnce sync.Once
	file_atlantis_common_v1_predicates_proto_rawDescData []byte
)

func file_atlantis_common_v1_predicates_proto_rawDescGZIP() []byte {
	file_atlantis_common_v1_predicates_proto_rawDescOnce.Do(func() {
		file_atlantis_common_v1_predicates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_predicates_proto_rawDesc), len(file_atlantis_common_v1_predicates_proto_rawDesc)))
	})
	return file_atlantis_common_v1_predicates_proto_rawDescData
}

var file_atlantis_common_v1_predicates_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_atlantis_common_v1_predicates_proto_goTypes = []any{
	(*StringPredicate)(nil),       // 0: atlantis.common.v1.StringPredicate
	(*Int32Predicate)(nil),        // 1: atlantis.common.v1.Int32Predicate
	(*Int64Predicate)(nil),        // 2: atlantis.common.v1.Int64Predicate
	(*BoolPredicate)(nil),         // 3: atlantis.common.v1.BoolPredicate
	(*TimestampPredicate)(nil),    // 4: atlantis.common.v1.TimestampPredicate
	(*BytesPredicate)(nil),        // 5: atlantis.common.v1.BytesPredicate
	(*NumericPredicate)(nil),      // 6: atlantis.common.v1.NumericPredicate
	(*FloatPredicate)(nil),        // 7: atlantis.common.v1.FloatPredicate
	(*DoublePredicate)(nil),       // 8: atlantis.common.v1.DoublePredicate
	(*StringList)(nil),            // 9: atlantis.common.v1.StringList
	(*Int32List)(nil),             // 10: atlantis.common.v1.Int32List
	(*Int64List)(nil),             // 11: atlantis.common.v1.Int64List
	(*BytesList)(nil),             // 12: atlantis.common.v1.BytesList
	(*FloatList)(nil),             // 13: atlantis.common.v1.FloatList
	(*DoubleList)(nil),            // 14: atlantis.common.v1.DoubleList
	(*Int32Range)(nil),            // 15: atlantis.common.v1.Int32Range
	(*Int64Range)(nil),            // 16: atlantis.common.v1.Int64Range
	(*TimestampRange)(nil),        // 17: atlantis.common.v1.TimestampRange
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_atlantis_common_v1_predicates_proto_depIdxs = []int32{
	9,  // 0: atlantis.common.v1.StringPredicate.in:type_name -> atlantis.common.v1.StringList
	9,  // 1: atlantis.common.v1.StringPredicate.not_in:type_name -> atlantis.common.v1.StringList
	10, // 2: atlantis.common.v1.Int32Predicate.in:type_name -> atlantis.common.v1.Int32List
	10, // 3: atlantis.common.v1.Int32Predicate.not_in:type_name -> atlantis.common.v1.Int32List
	15, // 4: atlantis.common.v1.Int32Predicate.between:type_name -> atlantis.common.v1.Int32Range
	11, // 5: atlantis.common.v1.Int64Predicate.in:type_name -> atlantis.common.v1.Int64List
	11, // 6: atlantis.common.v1.Int64Predicate.not_in:type_name -> atlantis.common.v1.Int64List
	16, // 7: atlantis.common.v1.Int64Predicate.between:type_name -> atlantis.common.v1.Int64Range
	18, // 8: atlantis.common.v1.TimestampPredicate.eq:type_name -> google.protobuf.Timestamp
	18, // 9: atlantis.common.v1.TimestampPredicate.neq:type_name -> google.protobuf.Timestamp
	18, // 10: atlantis.common.v1.TimestampPredicate.lt:type_name -> google.protobuf.Timestamp
	18, // 11: atlantis.common.v1.TimestampPredicate.lte:type_name -> google.protobuf.Timestamp
	18, // 12: atlantis.common.v1.TimestampPredicate.gt:type_name -> google.protobuf.Timestamp
	18, // 13: atlantis.common.v1.TimestampPredicate.gte:type_name -> google.protobuf.Timestamp
	17, // 14: atlantis.common.v1.TimestampPredicate.between:type_name -> atlantis.common.v1.TimestampRange
	12, // 15: atlantis.common.v1.BytesPredicate.in:type_name -> atlantis.common.v1.BytesList
	9,  // 16: atlantis.common.v1.NumericPredicate.in:type_name -> atlantis.common.v1.StringList
	13, // 17: atlantis.common.v1.FloatPredicate.in:type_name -> atlantis.common.v1.FloatList
	14, // 18: atlantis.common.v1.DoublePredicate.in:type_name -> atlantis.common.v1.DoubleList
	18, // 19: atlantis.common.v1.TimestampRange.lo:type_name -> google.protobuf.Timestamp
	18, // 20: atlantis.common.v1.TimestampRange.hi:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_atlantis_common_v1_predicates_proto_init() }
func file_atlantis_common_v1_predicates_proto_init() {
	if File_atlantis_common_v1_predicates_proto != nil {
		return
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[0].OneofWrappers = []any{
		(*StringPredicate_Eq)(nil),
		(*StringPredicate_Neq)(nil),
		(*StringPredicate_In)(nil),
		(*StringPredicate_NotIn)(nil),
		(*StringPredicate_Prefix)(nil),
		(*StringPredicate_Suffix)(nil),
		(*StringPredicate_Contains)(nil),
		(*StringPredicate_Ilike)(nil),
		(*StringPredicate_IsNull)(nil),
		(*StringPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[1].OneofWrappers = []any{
		(*Int32Predicate_Eq)(nil),
		(*Int32Predicate_Neq)(nil),
		(*Int32Predicate_Lt)(nil),
		(*Int32Predicate_Lte)(nil),
		(*Int32Predicate_Gt)(nil),
		(*Int32Predicate_Gte)(nil),
		(*Int32Predicate_In)(nil),
		(*Int32Predicate_NotIn)(nil),
		(*Int32Predicate_Between)(nil),
		(*Int32Predicate_IsNull)(nil),
		(*Int32Predicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[2].OneofWrappers = []any{
		(*Int64Predicate_Eq)(nil),
		(*Int64Predicate_Neq)(nil),
		(*Int64Predicate_Lt)(nil),
		(*Int64Predicate_Lte)(nil),
		(*Int64Predicate_Gt)(nil),
		(*Int64Predicate_Gte)(nil),
		(*Int64Predicate_In)(nil),
		(*Int64Predicate_NotIn)(nil),
		(*Int64Predicate_Between)(nil),
		(*Int64Predicate_IsNull)(nil),
		(*Int64Predicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[3].OneofWrappers = []any{
		(*BoolPredicate_Eq)(nil),
		(*BoolPredicate_IsNull)(nil),
		(*BoolPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[4].OneofWrappers = []any{
		(*TimestampPredicate_Eq)(nil),
		(*TimestampPredicate_Neq)(nil),
		(*TimestampPredicate_Lt)(nil),
		(*TimestampPredicate_Lte)(nil),
		(*TimestampPredicate_Gt)(nil),
		(*TimestampPredicate_Gte)(nil),
		(*TimestampPredicate_Between)(nil),
		(*TimestampPredicate_IsNull)(nil),
		(*TimestampPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[5].OneofWrappers = []any{
		(*BytesPredicate_Eq)(nil),
		(*BytesPredicate_Neq)(nil),
		(*BytesPredicate_In)(nil),
		(*BytesPredicate_IsNull)(nil),
		(*BytesPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[6].OneofWrappers = []any{
		(*NumericPredicate_Eq)(nil),
		(*NumericPredicate_Neq)(nil),
		(*NumericPredicate_Lt)(nil),
		(*NumericPredicate_Lte)(nil),
		(*NumericPredicate_Gt)(nil),
		(*NumericPredicate_Gte)(nil),
		(*NumericPredicate_In)(nil),
		(*NumericPredicate_IsNull)(nil),
		(*NumericPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[7].OneofWrappers = []any{
		(*FloatPredicate_Eq)(nil),
		(*FloatPredicate_Neq)(nil),
		(*FloatPredicate_Lt)(nil),
		(*FloatPredicate_Lte)(nil),
		(*FloatPredicate_Gt)(nil),
		(*FloatPredicate_Gte)(nil),
		(*FloatPredicate_In)(nil),
		(*FloatPredicate_IsNull)(nil),
		(*FloatPredicate_IsNotNull)(nil),
	}
	file_atlantis_common_v1_predicates_proto_msgTypes[8].OneofWrappers = []any{
		(*DoublePredicate_Eq)(nil),
		(*DoublePredicate_Neq)(nil),
		(*DoublePredicate_Lt)(nil),
		(*DoublePredicate_Lte)(nil),
		(*DoublePredicate_Gt)(nil),
		(*DoublePredicate_Gte)(nil),
		(*DoublePredicate_In)(nil),
		(*DoublePredicate_IsNull)(nil),
		(*DoublePredicate_IsNotNull)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlantis_common_v1_predicates_proto_rawDesc), len(file_atlantis_common_v1_predicates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atlantis_common_v1_predicates_proto_goTypes,
		DependencyIndexes: file_atlantis_common_v1_predicates_proto_depIdxs,
		MessageInfos:      file_atlantis_common_v1_predicates_proto_msgTypes,
	}.Build()
	File_atlantis_common_v1_predicates_proto = out.File
	file_atlantis_common_v1_predicates_proto_goTypes = nil
	file_atlantis_common_v1_predicates_proto_depIdxs = nil
}
