package codegen

import "strings"

// ProducedByBuf reports whether a path in a generated tree is protobuf output
// rather than emitter output.
//
// Two shapes, because the two languages put buf's output in different places.
// Go's lands under `pb/`, a directory no emitter writes into. Python's lands
// beside the clients that import it — protoc derives a module path from the
// proto path, so `atlantis.library.v1.book_pb2` resolves only from
// atlantis/library/v1/book_pb2.py.
//
// Two callers depend on this, and they fail differently when it is wrong:
//
//   - `tide generate --check` compares the committed tree against what the
//     emitters render. buf's output is not rendered, so a path this misses is
//     reported as a file the emitters dropped, and --check fails on a current
//     tree.
//   - the compilecheck fixture is regenerated by clearing what the emitters
//     own. A path this misses is deleted, and the next type-check runs over a
//     tree whose imports resolve to nothing.
func ProducedByBuf(path string) bool {
	if strings.HasPrefix(path, "pb/") {
		return true
	}
	for _, suffix := range []string{"_pb2.py", "_pb2.pyi", "_pb2_grpc.py", "_pb2_grpc.pyi"} {
		if strings.HasSuffix(path, suffix) {
			return true
		}
	}
	return false
}
