package codegen

import (
	"crypto/sha256"
	"encoding/hex"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// Proves, rather than argues, which DSL clauses have no effect on anything
// atlantis generates.
//
// A clause that parses and validates while producing no output gives its
// author no warning and a clean plan. Grepping for a field name cannot settle
// it: `Cache.Invalidate` has readers, and every one is either the differ
// comparing it or an unrelated method of the same name.
//
// So the test runs every emitter over two IRs differing only in the clause and
// compares the bytes. Identical output means the clause is inert, whatever the
// call graph suggests.
//
// The list below is a decision record, not a discovery: a clause named here has
// been examined and judged. Adding a clause to the grammar without adding it
// here fails TestEveryClauseIsAccountedFor.

// effectKind records what a clause actually does. The distinction between the
// last three is the whole value of this file: "changes no generated byte" and
// "has no effect" are different claims, and conflating them is how a clause
// gets removed that something needed, or kept that nothing uses.
type effectKind int

const (
	// emits: changes generated output that is compiled and shipped.
	emits effectKind = iota
	// emitsIntoDeadCode: changes generated output that nothing builds. The
	// clause looks implemented from inside codegen and does nothing in
	// production. This is the most dangerous state, because a source-level
	// audit finds the emitter and concludes the feature works.
	emitsIntoDeadCode
	// runtimeOnly: no codegen effect by design; the effect is at runtime, so
	// this test cannot see it and says nothing about whether it works.
	runtimeOnly
	// inert: no emitter output changes, and nothing consumes it at runtime.
	inert
)

type clauseEffect struct {
	kind effectKind
	// why records the judgement, and for anything but `emits`, the task that
	// resolves it.
	why string
}

// emitAll runs every generator over an IR and returns a digest of all output.
// A clause is inert exactly when two IRs differing only in it produce the same
// digest.
func emitAll(t *testing.T, ir *dsl.IR) string {
	t.Helper()

	var parts []string
	add := func(name string, fs []GoFile, err error) {
		if err != nil {
			// An emitter that refuses this IR is itself a difference worth
			// detecting, so it goes into the digest rather than failing.
			parts = append(parts, name+":ERR:"+err.Error())
			return
		}
		for _, f := range fs {
			parts = append(parts, name+":"+f.Path+":"+f.Content)
		}
	}

	fs, err := EmitGoServer(ir, GenConfig{})
	add("go-server", fs, err)
	fs, err = EmitGoClient(ir, testClientCfg)
	add("go-client", fs, err)
	fs, err = EmitGoCacheKeys(ir)
	add("go-keys", fs, err)
	fs, err = EmitCustomServer(ir, GenConfig{})
	add("custom-server", fs, err)
	fs, err = EmitCustomClient(ir, testClientCfg)
	add("custom-client", fs, err)
	fs, err = EmitJobsHandlers(ir)
	add("jobs", fs, err)
	fs, err = EmitWorkflows(ir)
	add("workflows", fs, err)
	fs, err = EmitEphemerals(ir)
	add("ephemerals", fs, err)

	addProto := func(name string, fs []ProtoFile, err error) {
		if err != nil {
			parts = append(parts, name+":ERR:"+err.Error())
			return
		}
		for _, f := range fs {
			parts = append(parts, name+":"+f.Path+":"+f.Content)
		}
	}
	pf, perr := EmitProto(ir)
	addProto("proto", pf, perr)
	cpf, cperr := EmitCustomProto(ir)
	addProto("custom-proto", cpf, cperr)

	// SQL, both the fresh-create and the migration path.
	if s, err := EmitInitial(ir); err != nil {
		parts = append(parts, "sql-initial:ERR:"+err.Error())
	} else {
		parts = append(parts, "sql-initial:"+s.Up+s.Down)
	}
	empty := &dsl.IR{}
	if s, err := EmitSQL(empty, ir, ComputeDiff(empty, ir)); err != nil {
		parts = append(parts, "sql-migration:ERR:"+err.Error())
	} else {
		parts = append(parts, "sql-migration:"+s.Up+s.Down)
	}

	sort.Strings(parts)
	sum := sha256.Sum256([]byte(strings.Join(parts, "\x00")))
	return hex.EncodeToString(sum[:])
}

// baseEntity is the fixture every case mutates. Deliberately ordinary — a
// clause that only matters on an exotic entity is not the kind this test is
// looking for.
func baseEntity() dsl.Entity {
	return dsl.Entity{
		Name: "Order", Namespace: "shop",
		Fields: []dsl.Field{
			{Name: "id", Type: dsl.FieldType{Name: "bigint"}, Primary: true},
			{Name: "total", Type: dsl.FieldType{Name: "int"}, NotNull: true},
			{Name: "note", Type: dsl.FieldType{Name: "text"}},
		},
	}
}

func withIR(e dsl.Entity) *dsl.IR { return &dsl.IR{Entities: []dsl.Entity{e}} }

// clauseCases pairs each clause with a mutation that turns it on.
var clauseCases = map[string]struct {
	mutate func(e *dsl.Entity)
	effect clauseEffect
}{

	"Relations (has_many/has_one/via)": {
		mutate: func(e *dsl.Entity) {
			e.Relations = []dsl.Relation{{
				Name: "items", Kind: dsl.RelHasMany, TargetID: "shop.Order", Via: "id",
			}}
		},
		effect: clauseEffect{
			kind: inert,
			why: "no emitter reads Entity.Relations and no runtime path consults it. Held " +
				"rather than removed: the IR already carries Name/Kind/TargetID/Via and " +
				"emitting an accessor is the same shape as the List RPCs codegen produces, " +
				"but a relation accessor is a NEW READ PATH and every generated read carries " +
				"a partition predicate, a soft-delete predicate, a query timeout and cache " +
				"keys. `partition by` fails open today, so building this now builds the leak " +
				"into a second surface. Task #14, blocked on tasks #11 and #29",
		},
	},
	"ChunkTimeIntervalMS": {
		mutate: func(e *dsl.Entity) {
			e.Kind = dsl.EntityKindHypertable
			e.TimeField = "note"
			e.ChunkTimeIntervalMS = 604800000
		},
		effect: clauseEffect{kind: emits, why: "passed to create_hypertable on create, and to set_chunk_time_interval on change"},
	},
	"Cache.Consistency": {
		mutate: func(e *dsl.Entity) {
			e.Cache = &dsl.Cache{HasReadThrough: true, TTLMS: 1000, Consistency: dsl.ConsistencyStrict}
		},
		effect: clauseEffect{kind: inert, why: "read-through strict-vs-eventual semantics, and no generated read consults the cache at all yet (the read cache is built but not wired into handleGet/handleQuery). Implemented alongside that wiring — task #14, plan 1h. Not a removal candidate: 0 corpus uses, but the semantics are wanted"},
	},
	"Cache.Invalidate (invalidate_on)": {
		mutate: func(e *dsl.Entity) {
			e.Cache = &dsl.Cache{
				HasReadThrough: true, TTLMS: 1000,
				Invalidate: []dsl.Invalidate{{Self: true}},
			}
		},
		effect: clauseEffect{kind: inert, why: "nothing reads Cache.Invalidate. Narrower than it looks: handler.go enqueues a self-invalidation on every write unconditionally, so the `write(self)` form that 9 of 10 corpus declarations use is already true in effect. Only cross-entity fan-out (`write(X where fk = self.id)`) is unimplemented, on top of a complete outbox+worker pipeline. Task #14 implements it"},
	},
	"Cache.Tag": {
		mutate: func(e *dsl.Entity) {
			e.Cache = &dsl.Cache{HasReadThrough: true, TTLMS: 1000, Tag: "order"}
		},
		effect: clauseEffect{kind: emits, why: "EmitGoCacheKeys generates a tag-key function from it"},
	},
	"Checks": {
		mutate: func(e *dsl.Entity) {
			e.Checks = []dsl.TableCheck{{Name: "total_positive", Expr: "total > 0"}}
		},
		effect: clauseEffect{kind: emits, why: "emitted as a table constraint, and diffed"},
	},
	"Field.Check": {
		mutate: func(e *dsl.Entity) { e.Fields[1].Check = "total > 0" },
		effect: clauseEffect{kind: emits, why: "inlined into the column definition"},
	},
	"SoftDeleteField": {
		mutate: func(e *dsl.Entity) { e.SoftDeleteField = "note" },
		effect: clauseEffect{kind: emits, why: "changes generated query predicates"},
	},
	"TouchOnUpdateField": {
		mutate: func(e *dsl.Entity) { e.TouchOnUpdateField = "note" },
		effect: clauseEffect{kind: emits, why: "emits a BEFORE UPDATE trigger"},
	},
	"TableName": {
		mutate: func(e *dsl.Entity) { e.TableName = "public.legacy_orders" },
		effect: clauseEffect{kind: emits, why: "changes the physical table every statement targets"},
	},
	"QueryTimeoutMS": {
		mutate: func(e *dsl.Entity) { e.QueryTimeoutMS = 5000 },
		effect: clauseEffect{kind: emits, why: "emitted into the generated server handlers"},
	},
	"CompositePK": {
		mutate: func(e *dsl.Entity) {
			e.Fields[0].Primary = false
			e.CompositePK = []string{"id", "total"}
		},
		effect: clauseEffect{kind: emits, why: "emitted as the table's PRIMARY KEY"},
	},
	"Indexes": {
		mutate: func(e *dsl.Entity) {
			e.Indexes = []dsl.Index{{Fields: []dsl.IndexField{{Name: "total"}}}}
		},
		effect: clauseEffect{kind: emits, why: "emitted as CREATE INDEX"},
	},
	"Uniques": {
		mutate: func(e *dsl.Entity) {
			e.Uniques = []dsl.UniqueSpec{{Fields: []string{"total", "note"}}}
		},
		effect: clauseEffect{kind: emits, why: "emitted as a composite UNIQUE constraint"},
	},
	"PartitionField": {
		mutate: func(e *dsl.Entity) { e.PartitionField = "total" },
		effect: clauseEffect{
			kind: emitsIntoDeadCode,
			why: "EmitGoServer does emit the predicate — `partitionVal, err := " +
				"runtime.CallerPartition(ctx)` into gen/go/server/<ns>/<entity>_server.go " +
				"— but that tree is not on disk and is not compiled: the server was " +
				"rewritten to dispatch from the IR at runtime and never carried this " +
				"layer across, and CallerPartition/WithCallerPartition have no callers " +
				"anywhere, so there was not even a value to inject. The documented " +
				"per-tenant guarantee failed open in production while looking " +
				"implemented from inside codegen.\n" +
				"\n" +
				"`partition by` is accepted again, and enforcement moved to the " +
				"database: codegen emits ENABLE/FORCE ROW LEVEL SECURITY and a policy " +
				"on atlantis.current_partition(). This entry stays because the DEAD Go " +
				"emitter is still present and would come back to life if anything " +
				"started compiling gen/go/server again — and a predicate in a file " +
				"nobody builds is exactly the shape of the original failure. The " +
				"isolation evidence lives in partition_rls_pg_test.go, which reads as " +
				"one tenant and fails to see another's row. Task #11 tracks deleting " +
				"the dead emitter and wiring set_partition into the request path.",
		},
	},
	"TtlField": {
		mutate: func(e *dsl.Entity) { e.TtlField = "note" },
		effect: clauseEffect{
			kind: runtimeOnly,
			why: "consumed by the TTL sweeper at runtime, not by any emitter, so this " +
				"test can say nothing about whether it works. It does not: the " +
				"sweeper's DELETE uses MySQL LIMIT syntax and errors every run — task " +
				"#13's sibling in the plan's 1h. Not a removal candidate; the clause " +
				"is right and the sweeper is wrong.",
		},
	},
}

// The headline: a clause marked inert must in fact change no generated byte,
// and a clause not marked inert must change at least one.
func TestClauseInertnessMatchesTheRecord(t *testing.T) {
	baseDigest := emitAll(t, withIR(baseEntity()))

	for name, tc := range clauseCases {
		t.Run(name, func(t *testing.T) {
			e := baseEntity()
			tc.mutate(&e)
			changed := emitAll(t, withIR(e)) != baseDigest

			wantChange := tc.effect.kind == emits || tc.effect.kind == emitsIntoDeadCode
			switch {
			case wantChange && !changed:
				t.Errorf("%s is recorded as changing generated output (%q), and every "+
					"emitter produces identical bytes with and without it.\n"+
					"  Either the effect was removed and nothing noticed, or the record "+
					"was never true. A clause that parses and emits nothing tells its "+
					"author their statement worked.", name, tc.effect.why)
			case !wantChange && changed:
				t.Errorf("%s is recorded as producing no generated output, and it does.\n"+
					"  Something now reads it. Update the record — and if this clause "+
					"was slated for removal, removing it is no longer safe.", name)
			}
		})
	}
}

// Anything that is not plainly emitted must name the task that resolves it.
// An inert clause is either being removed or is a bug being tracked; a clause
// emitting into dead code is a bug by definition; a runtime-only clause needs a
// pointer to where its behaviour actually lives. In every case there is a task,
// and a record without one decays into folklore.
func TestNonEmittingClausesNameATask(t *testing.T) {
	for name, tc := range clauseCases {
		if tc.effect.why == "" {
			t.Errorf("%s carries no reason", name)
			continue
		}
		if tc.effect.kind == emits {
			continue
		}
		if !strings.Contains(strings.ToLower(tc.effect.why), "task") {
			t.Errorf("%s does not plainly emit, and names no task: %q", name, tc.effect.why)
		}
	}
}

// The record must cover every entity-level attribute the grammar can set.
//
// Derived from dsl.Entity by reflection, so a clause added to the IR without a
// verdict here fails rather than passing unexamined — which is exactly how
// has_many, invalidate_on and consistency accumulated: each was added, each
// worked at parse time, and nothing ever asked what happened after that.
//
// Structural attributes (Name, Namespace, Fields) and codegen bookkeeping are
// exempt by name; everything else needs a case.
func TestEveryClauseIsAccountedFor(t *testing.T) {
	exempt := map[string]string{
		"Name":                "entity identity, not a clause",
		"Namespace":           "entity identity, not a clause",
		"Fields":              "the entity's columns; individual field modifiers are covered by their own cases",
		"Kind":                "entity vs hypertable — a declaration form rather than a clause, and an uncovered diff gap (see diff_coverage.go)",
		"RetiredProtoNumbers": "wire bookkeeping assigned by codegen, never authored",
		"TimeField":           "hypertable time column; only meaningful with Kind, which is itself exempt",
	}

	covered := map[string]bool{}
	for name := range clauseCases {
		// Case keys are prose ("Cache.Invalidate (invalidate_on)"), so match on
		// the leading identifier.
		covered[strings.Fields(strings.TrimPrefix(name, "Cache."))[0]] = true
		covered[strings.Fields(name)[0]] = true
	}

	typ := reflect.TypeOf(dsl.Entity{})
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		if !f.IsExported() || f.Anonymous {
			continue
		}
		if _, ok := exempt[f.Name]; ok {
			continue
		}
		if f.Name == "Cache" {
			// Covered field-by-field: the block as a whole is partly live
			// (Tag) and partly inert (Consistency, Invalidate), which is the
			// distinction worth recording.
			continue
		}
		if !covered[f.Name] {
			t.Errorf("dsl.Entity.%s has no entry in clauseCases.\n"+
				"  Add one saying what it emits, or that it emits nothing and which "+
				"task removes it. A clause nobody has asked that question about is "+
				"how has_many, invalidate_on and consistency all ended up parsing, "+
				"validating and doing nothing.", f.Name)
		}
	}
}
