package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/coltype"
	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitJobsHandlers renders one Go file per namespace that declares
// any `job` blocks. Each file holds, per job:
//
//   - A typed Args struct with one field per arg in the DSL block,
//     using the same Go-type mapping the entity codegen uses.
//   - A handler interface that takes the typed Args.
//   - A canonical JobName const matching the IR id.
//   - A Register<Job> helper that wraps a typed handler into the
//     untyped jobs.Handler the registry stores, deserializing args
//     JSON before invoking the typed method.
//
// The registering binary calls Register<Job> at startup for every job
// whose handler it owns. The worker looks up by JobName at claim time
// and invokes the registered untyped handler with the row's args JSON;
// the generated wrapper unmarshals into Args before dispatching.
//
// Two flavors share the emission: EmitJobsHandlers writes the server
// tree against the server-module jobs runtime, and
// EmitCallerJobsHandlers writes the caller client tree against the
// clients/go/jobs runtime a caller's DispatchedWorker uses. Submission
// stays untyped on both: a typed Submit<Job> needs a home for the admin
// gRPC client in the generated tree, which does not exist yet.
func EmitJobsHandlers(ir *dsl.IR) ([]GoFile, error) {
	return emitJobsHandlers(ir, "gen/go/server/%s/jobs.go",
		"github.com/rachitkumar205/atlantis/jobs")
}

// EmitCallerJobsHandlers renders the same per-namespace typed job
// surface into the caller's committed client tree, one client/<ns>/jobs.go
// per namespace declaring jobs. Register<Job> takes the *jobs.Registry a
// caller passes to jobs.NewDispatchedWorker.
func EmitCallerJobsHandlers(ir *dsl.IR) ([]GoFile, error) {
	return emitJobsHandlers(ir, "clients/go/client/%s/jobs.go",
		"github.com/rachitkumar205/atlantis/clients/go/jobs")
}

func emitJobsHandlers(ir *dsl.IR, pathFormat, jobsImport string) ([]GoFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitJobsHandlers: ir is required")
	}
	groups := groupJobsByNamespace(ir)
	if len(groups) == 0 {
		return nil, nil
	}
	out := make([]GoFile, 0, len(groups))
	for _, ns := range sortedJobNamespaceKeys(groups) {
		jobs := groups[ns]
		f, err := emitJobsForNamespace(ns, jobs, pathFormat, jobsImport)
		if err != nil {
			return nil, fmt.Errorf("jobs %s: %w", ns, err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func groupJobsByNamespace(ir *dsl.IR) map[string][]*dsl.Job {
	out := map[string][]*dsl.Job{}
	for i := range ir.Jobs {
		j := &ir.Jobs[i]
		out[j.Namespace] = append(out[j.Namespace], j)
	}
	for _, group := range out {
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })
	}
	return out
}

func sortedJobNamespaceKeys(m map[string][]*dsl.Job) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func emitJobsForNamespace(ns string, jobs []*dsl.Job, pathFormat, jobsImport string) (GoFile, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tide. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goNamespace(ns))

	// Compute imports up front. time.Time appears for a timestamptz or date
	// arg and pgtype.Interval for an interval one; the import-pruning keeps
	// the file lint-clean when every arg is a scalar.
	needsTime, needsPgtype := false, false
	for _, j := range jobs {
		for _, f := range j.Args {
			gt := coltype.GoType(f.Type, f.NotNull)
			if strings.Contains(gt, "time.") {
				needsTime = true
			}
			if strings.Contains(gt, "pgtype.") {
				needsPgtype = true
			}
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	if needsPgtype {
		b.WriteString("\t\"github.com/jackc/pgx/v5/pgtype\"\n")
	}
	b.WriteString("\t\"" + jobsImport + "\"\n")
	b.WriteString(")\n\n")

	// Reference all imports unconditionally so a job with zero args
	// (legal in the grammar) doesn't make json/fmt/context look unused.
	b.WriteString("var (\n")
	b.WriteString("\t_ = context.Background\n")
	b.WriteString("\t_ = json.Marshal\n")
	b.WriteString("\t_ = fmt.Sprintf\n")
	if needsTime {
		b.WriteString("\t_ = time.Time{}\n")
	}
	b.WriteString(")\n\n")

	for _, j := range jobs {
		if err := emitOneJob(&b, j); err != nil {
			return GoFile{}, err
		}
	}

	path := fmt.Sprintf(pathFormat, goNamespace(ns))
	return GoFile{Path: path, Content: b.String()}, nil
}

// emitOneJob writes the Args struct, Handler interface, JobName
// const, and Register helper for one job declaration. The four pieces
// stay co-located so a reader of the generated file sees the full
// surface for a given job kind in one place.
func emitOneJob(b *strings.Builder, j *dsl.Job) error {
	id := j.ID()

	// Args struct. Field names go to PascalCase; JSON tags preserve
	// the wire-side snake_case so the row's args JSON round-trips
	// cleanly across submit -> worker -> handler.
	fmt.Fprintf(b, "// %sArgs is the typed args struct for the %s job.\n", j.Name, id)
	fmt.Fprintf(b, "type %sArgs struct {\n", j.Name)
	for _, f := range j.Args {
		goTyp := coltype.GoType(f.Type, f.NotNull)
		fmt.Fprintf(b, "\t%-30s %s `json:%q`\n", pascalCaseJobField(f.Name), goTyp, f.Name)
	}
	b.WriteString("}\n\n")

	// Handler interface. Mirrors jobs.Handler but with the typed
	// Args parameter; the typed handler is the surface the caller
	// implements, and the wrapper below adapts to the registry's
	// untyped Handler signature at registration time.
	fmt.Fprintf(b, "// %sHandler is the typed handler interface for the %s job.\n", j.Name, id)
	fmt.Fprintf(b, "// Implement Handle and pass to Register%s at server startup.\n", j.Name)
	fmt.Fprintf(b, "type %sHandler interface {\n", j.Name)
	fmt.Fprintf(b, "\tHandle(ctx context.Context, args %sArgs) error\n", j.Name)
	b.WriteString("}\n\n")

	// JobName const. Used by callers who submit jobs via the admin
	// SubmitJob RPC; they pass this string as JobName.
	fmt.Fprintf(b, "// %sJobName is the canonical id used by SubmitJob.\n", j.Name)
	fmt.Fprintf(b, "const %sJobName = %q\n\n", j.Name, id)

	// Register helper. Adapts the typed handler into the untyped
	// jobs.Handler shape the registry stores. JSON unmarshal errors
	// bubble up to the worker, which records them on the row's
	// last_error column and retries until max_retries hits.
	fmt.Fprintf(b, "// Register%s binds h as the handler for the %s job.\n", j.Name, id)
	fmt.Fprintf(b, "// Call this once at server startup, before atlantis starts draining the queue.\n")
	fmt.Fprintf(b, "func Register%s(reg *jobs.Registry, h %sHandler) {\n", j.Name, j.Name)
	fmt.Fprintf(b, "\treg.Register(%sJobName, jobs.HandlerFunc(func(ctx context.Context, argsJSON []byte) error {\n", j.Name)
	fmt.Fprintf(b, "\t\tvar args %sArgs\n", j.Name)
	b.WriteString("\t\tif len(argsJSON) > 0 {\n")
	b.WriteString("\t\t\tif err := json.Unmarshal(argsJSON, &args); err != nil {\n")
	fmt.Fprintf(b, "\t\t\t\treturn fmt.Errorf(\"decode %sArgs: %%w\", err)\n", j.Name)
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn h.Handle(ctx, args)\n")
	b.WriteString("\t}))\n")
	b.WriteString("}\n\n")

	return nil
}

// pascalCaseJobField converts a snake_case arg name to a PascalCase
// Go field. Lower-case acronyms (ID, URL) stay snake-shaped here;
// callers tolerate "Id" / "Url" today and the entity codegen has the
// same compromise.
func pascalCaseJobField(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' {
			upper = true
			continue
		}
		if upper && r >= 'a' && r <= 'z' {
			r = r - ('a' - 'A')
		}
		b.WriteRune(r)
		upper = false
	}
	return b.String()
}
