package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/dsl"
	"github.com/rachitkumar205/atlantis/internal/schema"
)

// EmitPyClient renders the typed Python client that callers import. One file
// per entity, laid out to match the proto package so the generated protobuf
// modules sit beside it:
//
//	atlantis/library/v1/book_client.py
//
// Both flavours live in that one file — BookClient over a grpc.Channel and
// AsyncBookClient over a grpc.aio.Channel. One schema change is then one file
// in the caller's diff, whichever flavour they use.
//
// The proto messages are the value types. There is no generated dataclass
// layer: a second generated type system built from the same IR is a seventh
// mapping to keep in step with the six that already exist.
func EmitPyClient(ir *dsl.IR, cfg GenConfig) ([]PyFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitPyClient: ir is required")
	}
	var out []PyFile
	for i := range ir.Entities {
		e := &ir.Entities[i]
		if !servesAPI(e) {
			continue
		}
		f, err := emitPyClientEntity(e)
		if err != nil {
			return nil, fmt.Errorf("entity %s: %w", e.ID(), err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// pyBatchGetMaxIDs is the server's cap, refused client-side as well.
//
// A client-side check can name the number the caller passed; the server's
// reply carries only that the limit was exceeded. Refusing here does not
// replace the server's check, which is the one that is authoritative.
const pyBatchGetMaxIDs = 200

// pyEntityVerbs are the RPCs every entity serves, paired with the Python
// method name. The entity name is dropped — `books.get(...)` rather than
// `books.get_book(...)`, since the receiver already names the entity.
var pyEntityVerbs = []struct{ rpc, method string }{
	{"Get", "get"},
	{"BatchGet", "batch_get"},
	{"Create", "create"},
	{"Update", "update"},
	{"Delete", "delete"},
	{"Query", "query"},
}

func emitPyClientEntity(e *dsl.Entity) (PyFile, error) {
	ns := goNamespace(e.Namespace)
	mod := snakeCase(e.Name)

	var b strings.Builder
	b.WriteString("# Code generated by tide. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Typed client for %s.\"\"\"\n\n", e.ID())
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from typing import TYPE_CHECKING\n\n")
	b.WriteString("import grpc\n")
	b.WriteString("from atlantis_client import errors as _errors\n")
	b.WriteString("from atlantis_client import pagination as _pagination\n")
	if e.PartitionField != "" {
		b.WriteString("from atlantis_client import tenant as _tenant\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "from atlantis.%s.v1 import %s_pb2 as _pb\n", ns, mod)
	fmt.Fprintf(&b, "from atlantis.%s.v1 import %s_pb2_grpc as _pbg\n", ns, mod)
	b.WriteString("\nif TYPE_CHECKING:\n")
	b.WriteString("    from collections.abc import AsyncIterator, Iterator\n\n")

	emitPyCapabilities(&b, e)
	emitPyRejectHelper(&b, e)

	if err := emitPyEntityClass(&b, e, pyFlavourSync); err != nil {
		return PyFile{}, err
	}
	if err := emitPyEntityClass(&b, e, pyFlavourAsync); err != nil {
		return PyFile{}, err
	}

	path := fmt.Sprintf("atlantis/%s/v1/%s_client.py", ns, mod)
	return PyFile{Path: path, Content: b.String()}, nil
}

// emitPyCapabilities writes the per-entity constants naming what the server
// serves for this entity.
//
// `order` takes no constant: the dispatcher builds its keyset columns from the
// request's order, so there is nothing to refuse. A constant that is always
// true and guards nothing reads like a check and is not one.
func emitPyCapabilities(b *strings.Builder, e *dsl.Entity) {
	b.WriteString(`# What the server serves for this entity. Each guards one option below, so
# a release that implements one flips one constant.
SUPPORTS_FIELDS = False
SUPPORTS_INCLUDES = False

`)
	fmt.Fprintf(b, "# The server's cap on BatchGet, refused here so the error names the count.\nBATCH_GET_MAX_IDS = %d\n\n", pyBatchGetMaxIDs)
	_ = e
}

func emitPyRejectHelper(b *strings.Builder, e *dsl.Entity) {
	fmt.Fprintf(b, `def _check_query(request: _pb.Query%sRequest) -> None:
    """Refuse a query option the server does not serve.

    UnsupportedQueryOption is a ValueError, not an AtlantisError: the request
    is refused before a connection is used, so there is no status to carry.
    """
    if not SUPPORTS_FIELDS and request.HasField("fields"):
        raise _errors.UnsupportedQueryOption(
            "%s: the fields mask is not served; read the columns you need "
            "from the full row"
        )
    if not SUPPORTS_INCLUDES and len(request.includes) > 0:
        raise _errors.UnsupportedQueryOption(
            "%s: includes are not served; read the related entity with its "
            "own query"
        )


def _check_batch_get(request: _pb.BatchGet%sRequest) -> None:
    """Refuse more ids than the server accepts, naming how many were passed."""
    count = len(request.%s)
    if count > BATCH_GET_MAX_IDS:
        raise ValueError(
            f"%s: batch_get accepts at most {BATCH_GET_MAX_IDS} ids, got {count}"
        )


`, e.Name, e.ID(), e.ID(), e.Name, pyBatchGetIDsField(e), e.ID())
}

// pyBatchGetIDsField names the repeated field on BatchGet<E>Request.
//
// buildBatchGetRequest calls it `ids` for a composite key and `<pk>s` for a
// single one, so an entity keyed on `sku` carries `skus`. Guessing `ids`
// everywhere raises AttributeError on the second shape.
func pyBatchGetIDsField(e *dsl.Entity) string {
	pkCols := schema.PKColumns(e)
	if len(pkCols) != 1 {
		return "ids"
	}
	return pkCols[0].Name + "s"
}

type pyFlavour int

const (
	pyFlavourSync pyFlavour = iota
	pyFlavourAsync
)

func (f pyFlavour) className(entity string) string {
	if f == pyFlavourAsync {
		return "Async" + entity + "Client"
	}
	return entity + "Client"
}

func (f pyFlavour) channelType() string {
	if f == pyFlavourAsync {
		return "grpc.aio.Channel"
	}
	return "grpc.Channel"
}

func (f pyFlavour) def() string {
	if f == pyFlavourAsync {
		return "async def"
	}
	return "def"
}

func (f pyFlavour) await_() string {
	if f == pyFlavourAsync {
		return "await "
	}
	return ""
}

// emitPyEntityClass writes one flavour's class.
//
// Both flavours come from this one function rather than from two templates:
// the method set, the guards and the pagination contract are the same, and two
// near-copies is how the async one comes to lag the sync one by a fix.
func emitPyEntityClass(b *strings.Builder, e *dsl.Entity, f pyFlavour) error {
	cls := f.className(e.Name)
	partitioned := e.PartitionField != ""

	fmt.Fprintf(b, "class %s:\n", cls)
	fmt.Fprintf(b, "    \"\"\"%s over a %s.\"\"\"\n\n", e.ID(), f.channelType())

	// Constructor. A partitioned entity takes the tenant here rather than per
	// call: the header is required on every RPC, and Python has no compiler to
	// catch one call site that forgot it.
	if partitioned {
		fmt.Fprintf(b, `    def __init__(self, channel: %s, *, tenant: str) -> None:
        # %s declares `+"`partition by %s`"+`, so every call carries the
        # tenant header. Required here rather than per call: omitting it on one
        # call site fails at run time with Unauthenticated, which reads as a
        # credentials problem.
        self._stub = _pbg.%sServiceStub(channel)
        self._metadata = _tenant.metadata_for(tenant)

`, f.channelType(), e.ID(), e.PartitionField, e.Name)
	} else {
		fmt.Fprintf(b, `    def __init__(self, channel: %s) -> None:
        self._stub = _pbg.%sServiceStub(channel)
        self._metadata: tuple[tuple[str, str], ...] = ()

`, f.channelType(), e.Name)
	}

	for _, v := range pyEntityVerbs {
		emitPyEntityMethod(b, e, f, v.rpc, v.method)
	}
	emitPyQueryAll(b, e, f)

	for _, idx := range e.Indexes {
		if idx.Kind != dsl.IndexHNSW {
			continue
		}
		rpc := fmt.Sprintf("Search%sBy%s", e.Name, snakeToCamel(idx.Field))
		method := "search_by_" + snakeCase(idx.Field)
		fmt.Fprintf(b, `    %s self, request: _pb.%sRequest, *, timeout: float | None = None
    ) -> _pb.%sResponse:
        """Vector search over %s.%s."""
        try:
            return %sself._stub.%s(request, timeout=timeout, metadata=self._metadata)
        except grpc.RpcError as exc:
            raise _errors.translate(exc) from exc

`, f.def()+" "+method+"(", rpc, rpc, e.ID(), idx.Field, f.await_(), rpc)
	}

	b.WriteString("\n")
	return nil
}

func emitPyEntityMethod(b *strings.Builder, e *dsl.Entity, f pyFlavour, rpc, method string) {
	var guard string
	switch rpc {
	case "Query":
		guard = "        _check_query(request)\n"
	case "BatchGet":
		guard = "        _check_batch_get(request)\n"
	}

	fmt.Fprintf(b, `    %s %s(
        self, request: _pb.%s%sRequest, *, timeout: float | None = None
    ) -> _pb.%s%sResponse:
        """%s%s."""
%s        try:
            return %sself._stub.%s%s(
                request, timeout=timeout, metadata=self._metadata
            )
        except grpc.RpcError as exc:
            raise _errors.translate(exc) from exc

`, f.def(), method, rpc, e.Name, rpc, e.Name, rpc, e.Name, guard,
		f.await_(), rpc, e.Name)
}

// emitPyQueryAll writes the paging helper.
//
// It copies the request before setting page_token, so a caller reusing one
// request object across calls does not find it carrying the last page's token.
func emitPyQueryAll(b *strings.Builder, e *dsl.Entity, f pyFlavour) {
	if f == pyFlavourAsync {
		fmt.Fprintf(b, `    def query_all(
        self, request: _pb.Query%sRequest, *, timeout: float | None = None
    ) -> AsyncIterator[_pb.%s]:
        """Every row matching request, following next_page_token.

        Stops only on an empty token. A page shorter than the limit does not
        end the walk: the server clamps limit to %d, so a full result set
        arrives short with more still to read.

        Send the same `+"`order`"+` for the whole walk — a page token is only
        valid under the ordering it was issued for.
        """
        _check_query(request)

        async def fetch(token: str) -> _pb.Query%sResponse:
            page = _pb.Query%sRequest()
            page.CopyFrom(request)
            page.page_token = token
            try:
                return await self._stub.Query%s(
                    page, timeout=timeout, metadata=self._metadata
                )
            except grpc.RpcError as exc:
                raise _errors.translate(exc) from exc

        return _pagination.aiterate_pages(fetch, lambda page: page.entities)

`, e.Name, e.Name, pyServerMaxLimit, e.Name, e.Name, e.Name)
		return
	}

	fmt.Fprintf(b, `    def query_all(
        self, request: _pb.Query%sRequest, *, timeout: float | None = None
    ) -> Iterator[_pb.%s]:
        """Every row matching request, following next_page_token.

        Stops only on an empty token. A page shorter than the limit does not
        end the walk: the server clamps limit to %d, so a full result set
        arrives short with more still to read.

        Send the same `+"`order`"+` for the whole walk — a page token is only
        valid under the ordering it was issued for.
        """
        _check_query(request)

        def fetch(token: str) -> _pb.Query%sResponse:
            page = _pb.Query%sRequest()
            page.CopyFrom(request)
            page.page_token = token
            try:
                return self._stub.Query%s(
                    page, timeout=timeout, metadata=self._metadata
                )
            except grpc.RpcError as exc:
                raise _errors.translate(exc) from exc

        return _pagination.iterate_pages(fetch, lambda page: page.entities)

`, e.Name, e.Name, pyServerMaxLimit, e.Name, e.Name, e.Name)
}

// pyServerMaxLimit mirrors the dispatcher's clamp, for the docstring that
// explains a short page.
const pyServerMaxLimit = queryMaxLimit
