package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitPyCustomClient renders one custom_client.py per namespace declaring a
// custom query or procedure, mirroring EmitCustomClient's grouping.
//
// Queries and procedures share one CustomService, so they share one class.
func EmitPyCustomClient(ir *dsl.IR) ([]PyFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitPyCustomClient: ir is required")
	}
	groups := groupCustomByNamespace(ir)
	if len(groups) == 0 {
		return nil, nil
	}
	out := make([]PyFile, 0, len(groups))
	for _, ns := range sortedKeys(groups) {
		out = append(out, emitPyCustomForNamespace(ns, groups[ns]))
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// pyCustomCall is one RPC on the namespace's CustomService.
type pyCustomCall struct {
	rpc    string
	method string
	doc    string
}

func customCalls(g *customGroup) []pyCustomCall {
	calls := make([]pyCustomCall, 0, len(g.Queries)+len(g.Procedures))
	for _, q := range g.Queries {
		calls = append(calls, pyCustomCall{
			rpc:    q.Name,
			method: snakeCase(q.Name),
			doc:    fmt.Sprintf("The %s custom query.", q.Name),
		})
	}
	for _, p := range g.Procedures {
		calls = append(calls, pyCustomCall{
			rpc:    p.Name,
			method: snakeCase(p.Name),
			doc:    fmt.Sprintf("The %s custom procedure. Runs its steps in one transaction.", p.Name),
		})
	}
	sort.Slice(calls, func(i, j int) bool { return calls[i].rpc < calls[j].rpc })
	return calls
}

func emitPyCustomForNamespace(ns string, g *customGroup) PyFile {
	gons := goNamespace(ns)
	calls := customCalls(g)

	var b strings.Builder
	b.WriteString("# Code generated by tide. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Custom queries and procedures for the %s namespace.\"\"\"\n\n", gons)
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("import grpc\n")
	b.WriteString("from atlantis_client import errors as _errors\n\n")
	fmt.Fprintf(&b, "from atlantis.%s.v1 import custom_pb2 as _pb\n", gons)
	fmt.Fprintf(&b, "from atlantis.%s.v1 import custom_pb2_grpc as _pbg\n\n", gons)

	// A custom declaration is not addressed by tenant. Its SQL runs inside a
	// transaction the server binds from the request's own tenant header when
	// any entity it touches is partitioned, so the header travels with the
	// channel's caller rather than with this class.
	for _, f := range []pyFlavour{pyFlavourSync, pyFlavourAsync} {
		cls := "CustomClient"
		if f == pyFlavourAsync {
			cls = "AsyncCustomClient"
		}
		fmt.Fprintf(&b, "class %s:\n", cls)
		fmt.Fprintf(&b, "    \"\"\"Custom SQL for %s, over a %s.\"\"\"\n\n", gons, f.channelType())
		fmt.Fprintf(&b, `    def __init__(self, channel: %s) -> None:
        self._stub = _pbg.CustomServiceStub(channel)

`, f.channelType())
		for _, c := range calls {
			fmt.Fprintf(&b, `    %s %s(
        self, request: _pb.%sRequest, *, timeout: float | None = None
    ) -> _pb.%sResponse:
        """%s"""
        try:
            return %sself._stub.%s(request, timeout=timeout)
        except grpc.RpcError as exc:
            raise _errors.translate(exc) from exc

`, f.def(), c.method, c.rpc, c.rpc, c.doc, f.await_(), c.rpc)
		}
		b.WriteString("\n")
	}

	return PyFile{
		Path:    fmt.Sprintf("atlantis/%s/v1/custom_client.py", gons),
		Content: b.String(),
	}
}
