package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/coltype"
	"github.com/rachitkumar205/atlantis/internal/dsl"
	"github.com/rachitkumar205/atlantis/internal/schema"
)

// EmitPyJobsHandlers renders one jobs.py per namespace declaring any `job`
// blocks, the Python counterpart of EmitCallerJobsHandlers. Each file holds,
// per job: a frozen dataclass of its args, a Handler type alias, the
// canonical job name, and a register_<job> that binds a typed handler to the
// untyped one atlantis_client.jobs.Registry stores.
//
// The args come off the wire as JSON, so the annotations are PyJSONType's,
// not PyType's — a `timestamptz` arg is a str here and a Timestamp message on
// the data plane.
func EmitPyJobsHandlers(ir *dsl.IR) ([]PyFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitPyJobsHandlers: ir is required")
	}
	groups := groupJobsByNamespace(ir)
	if len(groups) == 0 {
		return nil, nil
	}
	out := make([]PyFile, 0, len(groups))
	for _, ns := range sortedJobNamespaceKeys(groups) {
		f, err := emitPyJobsForNamespace(ns, groups[ns])
		if err != nil {
			return nil, fmt.Errorf("python jobs %s: %w", ns, err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// pyJobArg is one arg with its annotation resolved.
type pyJobArg struct {
	name     string
	pyType   string
	nullable bool
}

func pyJobArgs(j *dsl.Job) ([]pyJobArg, error) {
	args := make([]pyJobArg, 0, len(j.Args))
	for _, f := range j.Args {
		t, err := coltype.PyJSONType(f.Type, f.NotNull)
		if err != nil {
			return nil, fmt.Errorf("job %s arg %s: %w", j.Name, f.Name, err)
		}
		args = append(args, pyJobArg{name: f.Name, pyType: t, nullable: !f.NotNull})
	}
	return args, nil
}

func emitPyJobsForNamespace(ns string, jobs []*dsl.Job) (PyFile, error) {
	gons := goNamespace(ns)

	resolved := make([][]pyJobArg, len(jobs))
	needsInterval, needsSequence := false, false
	for i, j := range jobs {
		args, err := pyJobArgs(j)
		if err != nil {
			return PyFile{}, err
		}
		resolved[i] = args
		for _, a := range args {
			if strings.Contains(a.pyType, "IntervalJSON") {
				needsInterval = true
			}
			if strings.Contains(a.pyType, "Sequence[") {
				needsSequence = true
			}
		}
	}

	var b strings.Builder
	b.WriteString("# Code generated by tide. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Typed job handlers for the %s namespace.\"\"\"\n\n", gons)
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from collections.abc import Callable, Mapping")
	if needsSequence {
		b.WriteString(", Sequence")
	}
	b.WriteString("\n")
	b.WriteString("from dataclasses import dataclass\n")
	b.WriteString("from typing import Any\n\n")
	b.WriteString("from atlantis_client.jobs import Registry\n")
	if needsInterval {
		b.WriteString("from atlantis_client.jobs.argjson import IntervalJSON\n")
	}
	b.WriteString("\n")

	for i, j := range jobs {
		emitOnePyJob(&b, j, resolved[i])
	}

	return PyFile{
		Path:    fmt.Sprintf("atlantis/%s/v1/jobs.py", gons),
		Content: b.String(),
	}, nil
}

func emitOnePyJob(b *strings.Builder, j *dsl.Job, args []pyJobArg) {
	id := j.ID()
	cls := j.Name + "Args"

	fmt.Fprintf(b, "%s_JOB_NAME = %q\n\n\n", schema.ScreamingSnake(j.Name), id)

	// frozen because a handler that mutates its args changes nothing the
	// server will see; the row's args stay as submitted.
	//
	// No field carries a default, so the args keep their declared order and
	// adding a nullable one does not have to move it past the not-null ones.
	b.WriteString("@dataclass(frozen=True)\n")
	fmt.Fprintf(b, "class %s:\n", cls)
	fmt.Fprintf(b, "    \"\"\"Args for the %s job.\"\"\"\n\n", id)
	if len(args) == 0 {
		b.WriteString("    pass\n\n")
	}
	for _, a := range args {
		fmt.Fprintf(b, "    %s: %s\n", a.name, a.pyType)
	}
	b.WriteString("\n")

	// A not-null arg is read with [] so a missing key raises KeyError naming
	// it. The worker reports that as a job failure; reading it as None would
	// hand the handler an absent value the schema says cannot occur.
	fmt.Fprintf(b, "    @classmethod\n")
	fmt.Fprintf(b, "    def from_json(cls, args: Mapping[str, Any]) -> %s:\n", cls)
	fmt.Fprintf(b, "        \"\"\"Build from one row's decoded args.\"\"\"\n")
	if len(args) == 0 {
		b.WriteString("        return cls()\n\n\n")
	} else {
		b.WriteString("        return cls(\n")
		for _, a := range args {
			if a.nullable {
				fmt.Fprintf(b, "            %s=args.get(%q),\n", a.name, a.name)
			} else {
				fmt.Fprintf(b, "            %s=args[%q],\n", a.name, a.name)
			}
		}
		b.WriteString("        )\n\n\n")
	}

	fmt.Fprintf(b, "%sHandler = Callable[[%s], None]\n\n\n", j.Name, cls)

	fmt.Fprintf(b, "def register_%s(registry: Registry, handler: %sHandler) -> None:\n",
		snakeCase(j.Name), j.Name)
	fmt.Fprintf(b, "    \"\"\"Bind handler to the %s job.\n\n", id)
	b.WriteString("    Call before starting the worker: DispatchedWorker declares the\n")
	b.WriteString("    registry's job names in its Open, and the server dispatches only\n")
	b.WriteString("    what was declared.\n")
	b.WriteString("    \"\"\"\n")
	fmt.Fprintf(b, "    registry.register(\n")
	fmt.Fprintf(b, "        %s_JOB_NAME,\n", schema.ScreamingSnake(j.Name))
	fmt.Fprintf(b, "        lambda args: handler(%s.from_json(args)),\n", cls)
	b.WriteString("    )\n\n\n")
}
