package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitPyPackages renders the __init__.py for every directory the generated
// Python tree occupies, plus the py.typed marker.
//
// Python needs these to exist. protoc writes .py files into
// atlantis/<ns>/v1/ and nothing else creates the packages above them, so
// without this the caller's own code cannot import what tide just wrote —
// a regular package with no __init__.py is only importable as a namespace
// package, which shadows badly and does not carry py.typed.
//
// Each leaf __init__.py re-exports its entities' clients and their request and
// response messages, so a caller writes one import per namespace rather than
// one per entity and one per message module.
func EmitPyPackages(ir *dsl.IR) ([]PyFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitPyPackages: ir is required")
	}

	byNamespace := map[string][]*dsl.Entity{}
	for i := range ir.Entities {
		e := &ir.Entities[i]
		if !servesAPI(e) {
			continue
		}
		ns := goNamespace(e.Namespace)
		byNamespace[ns] = append(byNamespace[ns], e)
	}
	for _, group := range byNamespace {
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })
	}

	// Namespaces carrying only custom SQL still need their package. A caller
	// declaring `query` blocks and no entity would otherwise get a directory
	// holding a custom_client.py that nothing can import.
	custom := groupCustomByNamespace(ir)
	for ns := range custom {
		gons := goNamespace(ns)
		if _, seen := byNamespace[gons]; !seen {
			byNamespace[gons] = nil
		}
	}

	namespaces := make([]string, 0, len(byNamespace))
	for ns := range byNamespace {
		namespaces = append(namespaces, ns)
	}
	sort.Strings(namespaces)

	out := []PyFile{
		{Path: "atlantis/__init__.py", Content: pyRootInit(namespaces)},
		// py.typed rides at the root of the generated tree. PEP 561 reads it
		// per top-level package, so one marker covers every namespace under
		// it; without it a caller's mypy ignores every annotation here.
		{Path: "atlantis/py.typed", Content: ""},
		{Path: "atlantis/common/__init__.py", Content: pyPackageInit("Shared predicate and pagination messages.")},
		{Path: "atlantis/common/v1/__init__.py", Content: pyPackageInit("Shared predicate and pagination messages.")},
	}

	for _, ns := range namespaces {
		out = append(out, PyFile{
			Path:    fmt.Sprintf("atlantis/%s/__init__.py", ns),
			Content: pyPackageInit(fmt.Sprintf("The %s namespace.", ns)),
		})
		out = append(out, PyFile{
			Path:    fmt.Sprintf("atlantis/%s/v1/__init__.py", ns),
			Content: pyNamespaceInit(ns, byNamespace[ns], custom),
		})
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func pyPackageInit(doc string) string {
	return "# Code generated by tide. DO NOT EDIT.\n\"\"\"" + doc + "\"\"\"\n"
}

func pyRootInit(namespaces []string) string {
	var b strings.Builder
	b.WriteString("# Code generated by tide. DO NOT EDIT.\n")
	b.WriteString("\"\"\"The typed Python client for this schema.\n\n")
	b.WriteString("One subpackage per namespace:\n\n")
	for _, ns := range namespaces {
		fmt.Fprintf(&b, "    atlantis.%s.v1\n", ns)
	}
	b.WriteString("\nThe runtime these import is the atlantis-client distribution.\n\"\"\"\n")
	return b.String()
}

// pyNamespaceInit re-exports one namespace's clients and messages.
//
// The message modules are re-exported by name rather than with a star import:
// two entities in one namespace both declare a `QueryXRequest`, and a star
// import makes which one a caller gets depend on module order.
func pyNamespaceInit(ns string, entities []*dsl.Entity, custom map[string]*customGroup) string {
	var b strings.Builder
	b.WriteString("# Code generated by tide. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "\"\"\"Typed clients for the %s namespace.\"\"\"\n\n", ns)
	b.WriteString("from __future__ import annotations\n\n")

	names := make([]string, 0, len(entities)*3)
	for _, e := range entities {
		mod := snakeCase(e.Name)
		fmt.Fprintf(&b, "from atlantis.%s.v1 import %s_pb2 as %s\n", ns, mod, mod)
		fmt.Fprintf(&b, "from atlantis.%s.v1.%s_client import Async%sClient, %sClient\n",
			ns, mod, e.Name, e.Name)
		names = append(names, mod, e.Name+"Client", "Async"+e.Name+"Client")
	}

	if namespaceHasCustom(ns, custom) {
		fmt.Fprintf(&b, "from atlantis.%s.v1.custom_client import AsyncCustomClient, CustomClient\n", ns)
		names = append(names, "CustomClient", "AsyncCustomClient")
	}

	sort.Strings(names)
	b.WriteString("\n__all__ = [\n")
	for _, n := range names {
		fmt.Fprintf(&b, "    %q,\n", n)
	}
	b.WriteString("]\n")
	return b.String()
}

// namespaceHasCustom reports whether ns — already mapped through goNamespace —
// declares a custom query or procedure.
//
// The map is keyed by the raw DSL namespace, so the comparison maps each key
// rather than the argument: `vendor` becomes `vendorpkg` on the way to Python,
// and comparing the two directly finds nothing for exactly one namespace.
func namespaceHasCustom(ns string, custom map[string]*customGroup) bool {
	for raw := range custom {
		if goNamespace(raw) == ns {
			return true
		}
	}
	return false
}
