"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Interval is the wire form of a Postgres INTERVAL column.

# Why not google.protobuf.Duration

Duration is seconds plus nanos — one magnitude. A Postgres interval is
three, and they are not interconvertible: '1 mon' is 28, 29, 30 or 31 days
depending on which month it is added to, and '1 day' is 23, 24 or 25 hours
across a daylight-saving boundary. Postgres keeps months, days and
microseconds apart precisely so it does not have to guess, and pgtype.Interval
mirrors that.

Collapsing them to a Duration would mean picking a month length at the wire
boundary and writing the guess into the caller's data. For a layer whose job
is to be faithful to what Postgres stores, that is the wrong trade at any
price — so the wire type mirrors the storage type instead.

# What this replaces

Before this existed, `interval` had four different representations and no two
agreed: coltype.ProtoType said google.protobuf.Duration, coltype.GoType said
time.Duration, coltype.ScanFragments declared a `string` and assigned it
straight to the proto field, and the dynamic dispatcher published TYPE_STRING.
The generated code did not compile, which is why nobody had noticed that the
four disagreed.
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import typing as _typing

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
