"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Interval is the wire form of a Postgres INTERVAL column.

# Why not google.protobuf.Duration

Duration is seconds plus nanos — one magnitude. A Postgres interval is
three, and they are not interconvertible: '1 mon' is 28, 29, 30 or 31 days
depending on which month it is added to, and '1 day' is 23, 24 or 25 hours
across a daylight-saving boundary. Postgres keeps months, days and
microseconds apart precisely so it does not have to guess, and pgtype.Interval
mirrors that.

Collapsing them to a Duration would mean picking a month length at the wire
boundary and writing the guess into the caller's data. For a layer whose job
is to be faithful to what Postgres stores, that is the wrong trade at any
price — so the wire type mirrors the storage type instead.

# What this replaces

Before this existed, `interval` had four different representations and no two
agreed: coltype.ProtoType said google.protobuf.Duration, coltype.GoType said
time.Duration, coltype.ScanFragments declared a `string` and assigned it
straight to the proto field, and the dynamic dispatcher published TYPE_STRING.
The generated code did not compile, which is why nobody had noticed that the
four disagreed.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Interval(_message.Message):
    """Interval carries the three components Postgres stores, unmodified.

    The signs are independent and all three may be negative: '1 mon -3 days' is a
    legal interval and round-trips as months=1, days=-3.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MONTHS_FIELD_NUMBER: _builtins.int
    DAYS_FIELD_NUMBER: _builtins.int
    MICROSECONDS_FIELD_NUMBER: _builtins.int
    months: _builtins.int
    """Whole months. Years are months*12 — Postgres normalizes '1 year' to
    12 months on input, so no separate field is needed.
    """
    days: _builtins.int
    """Whole days, kept apart from microseconds because a day is not always
    86_400_000_000 microseconds.
    """
    microseconds: _builtins.int
    """Everything below a day: hours, minutes, seconds and fractional seconds,
    as a single microsecond count. Postgres stores this resolution exactly,
    and int64 microseconds covers the full range it accepts.
    """
    def __init__(
        self,
        *,
        months: _builtins.int = ...,
        days: _builtins.int = ...,
        microseconds: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["days", b"days", "microseconds", b"microseconds", "months", b"months"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Interval: _TypeAlias = Interval  # noqa: Y015
