# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atlantis/common/v1/pagination.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'atlantis/common/v1/pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#atlantis/common/v1/pagination.proto\x12\x12\x61tlantis.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\tPageToken\x12\x1b\n\tentity_id\x18\x01 \x01(\tR\x08\x65ntityId\x12:\n\x06values\x18\x02 \x03(\x0b\x32\".atlantis.common.v1.PageTokenValueR\x06values\"\xb1\x01\n\x0ePageTokenValue\x12\x0e\n\x01s\x18\x01 \x01(\tH\x00R\x01s\x12\x0e\n\x01i\x18\x02 \x01(\x03H\x00R\x01i\x12\x0e\n\x01\x62\x18\x03 \x01(\x08H\x00R\x01\x62\x12,\n\x02ts\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\x02ts\x12\x12\n\x03raw\x18\x05 \x01(\x0cH\x00R\x03raw\x12\x12\n\x03num\x18\x06 \x01(\tH\x00R\x03num\x12\x14\n\x04null\x18\x07 \x01(\x08H\x00R\x04nullB\x03\n\x01vB\x05\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atlantis.common.v1.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\002'
  _globals['_PAGETOKEN']._serialized_start=92
  _globals['_PAGETOKEN']._serialized_end=192
  _globals['_PAGETOKENVALUE']._serialized_start=195
  _globals['_PAGETOKENVALUE']._serialized_end=372
# @@protoc_insertion_point(module_scope)
