"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
PageToken is an opaque keyset cursor returned in QueryXResponse and
echoed back unchanged. The embedded entity_id prevents using a
cursor from one entity against another.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PageToken(_message.Message):
    """PageToken carries the ORDER BY values + PK tiebreaker of the last
    row of a page. entity_id is "<namespace>.<EntityName>"; the decoder
    rejects cursors whose entity_id doesn't match the current request.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ENTITY_ID_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    entity_id: _builtins.str
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___PageTokenValue]: ...
    def __init__(
        self,
        *,
        entity_id: _builtins.str = ...,
        values: _abc.Iterable[Global___PageTokenValue] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entity_id", b"entity_id", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageToken: _TypeAlias = PageToken  # noqa: Y015

@_typing.final
class PageTokenValue(_message.Message):
    """One value per ORDER BY column plus PK tiebreaker. Numeric is sent
    as decimal string (gRPC has no arbitrary-precision decimal).
    """

    DESCRIPTOR: _descriptor.Descriptor

    S_FIELD_NUMBER: _builtins.int
    I_FIELD_NUMBER: _builtins.int
    B_FIELD_NUMBER: _builtins.int
    TS_FIELD_NUMBER: _builtins.int
    RAW_FIELD_NUMBER: _builtins.int
    NUM_FIELD_NUMBER: _builtins.int
    NULL_FIELD_NUMBER: _builtins.int
    s: _builtins.str
    i: _builtins.int
    b: _builtins.bool
    raw: _builtins.bytes
    num: _builtins.str
    null: _builtins.bool
    """A NULL ordering key.

    The ARM's presence is the whole signal; the bool carries nothing and
    is always true. It cannot be expressed by omitting the value instead:
    a PageToken holds one entry per ORDER BY column positionally, so a
    missing entry would shift every later column onto the wrong one.

    A distinct arm is also what keeps NULL distinguishable from a real
    zero. Before this existed, an unset optional scalar reached the cursor
    as 0 or "" and the encoder could not tell the two apart, so a page
    boundary landing on a NULL was written as a value that compares
    in-range — which is how rows past it became unreachable.
    """
    @_builtins.property
    def ts(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        s: _builtins.str = ...,
        i: _builtins.int = ...,
        b: _builtins.bool = ...,
        ts: _timestamp_pb2.Timestamp = ...,
        raw: _builtins.bytes = ...,
        num: _builtins.str = ...,
        null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["b", b"b", "i", b"i", "null", b"null", "num", b"num", "raw", b"raw", "s", b"s", "ts", b"ts", "v", b"v"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["b", b"b", "i", b"i", "null", b"null", "num", b"num", "raw", b"raw", "s", b"s", "ts", b"ts", "v", b"v"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_v: _TypeAlias = _typing.Literal["s", "i", "b", "ts", "raw", "num", "null"]  # noqa: Y015
    _WhichOneofArgType_v: _TypeAlias = _typing.Literal["v", b"v"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_v) -> _WhichOneofReturnType_v | None: ...

Global___PageTokenValue: _TypeAlias = PageTokenValue  # noqa: Y015
