"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Shared predicate messages. Entity codegen embeds these in QueryXFilter;
the runtime translator (internal/codegen/query/translator.go) walks the
set oneof arm to build the SQL fragment.

New `op` arms must take the next free number; reuse a number only after
the old arm has a 'reserved' line.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StringPredicate(_message.Message):
    """StringPredicate covers text / varchar / citext / uuid. The LIKE-flavored
    arms (prefix/suffix/contains/ilike) escape `%` and `_` in caller input.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    NOT_IN_FIELD_NUMBER: _builtins.int
    PREFIX_FIELD_NUMBER: _builtins.int
    SUFFIX_FIELD_NUMBER: _builtins.int
    CONTAINS_FIELD_NUMBER: _builtins.int
    ILIKE_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.str
    neq: _builtins.str
    prefix: _builtins.str
    suffix: _builtins.str
    contains: _builtins.str
    ilike: _builtins.str
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    @_builtins.property
    def not_in(self) -> Global___StringList: ...
    def __init__(
        self,
        *,
        eq: _builtins.str = ...,
        neq: _builtins.str = ...,
        not_in: Global___StringList = ...,
        prefix: _builtins.str = ...,
        suffix: _builtins.str = ...,
        contains: _builtins.str = ...,
        ilike: _builtins.str = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["contains", b"contains", "eq", b"eq", "ilike", b"ilike", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "neq", b"neq", "not_in", b"not_in", "op", b"op", "prefix", b"prefix", "suffix", b"suffix"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["contains", b"contains", "eq", b"eq", "ilike", b"ilike", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "neq", b"neq", "not_in", b"not_in", "op", b"op", "prefix", b"prefix", "suffix", b"suffix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "in", "not_in", "prefix", "suffix", "contains", "ilike", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___StringPredicate: _TypeAlias = StringPredicate  # noqa: Y015

@_typing.final
class Int32Predicate(_message.Message):
    """Int32Predicate handles smallint + int. `between` is inclusive;
    lo > hi is rejected (likely caller bug).
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    NOT_IN_FIELD_NUMBER: _builtins.int
    BETWEEN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.int
    neq: _builtins.int
    lt: _builtins.int
    lte: _builtins.int
    gt: _builtins.int
    gte: _builtins.int
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    @_builtins.property
    def not_in(self) -> Global___Int32List: ...
    @_builtins.property
    def between(self) -> Global___Int32Range: ...
    def __init__(
        self,
        *,
        eq: _builtins.int = ...,
        neq: _builtins.int = ...,
        lt: _builtins.int = ...,
        lte: _builtins.int = ...,
        gt: _builtins.int = ...,
        gte: _builtins.int = ...,
        not_in: Global___Int32List = ...,
        between: Global___Int32Range = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "not_in", b"not_in", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "not_in", b"not_in", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "in", "not_in", "between", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___Int32Predicate: _TypeAlias = Int32Predicate  # noqa: Y015

@_typing.final
class Int64Predicate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    NOT_IN_FIELD_NUMBER: _builtins.int
    BETWEEN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.int
    neq: _builtins.int
    lt: _builtins.int
    lte: _builtins.int
    gt: _builtins.int
    gte: _builtins.int
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    @_builtins.property
    def not_in(self) -> Global___Int64List: ...
    @_builtins.property
    def between(self) -> Global___Int64Range: ...
    def __init__(
        self,
        *,
        eq: _builtins.int = ...,
        neq: _builtins.int = ...,
        lt: _builtins.int = ...,
        lte: _builtins.int = ...,
        gt: _builtins.int = ...,
        gte: _builtins.int = ...,
        not_in: Global___Int64List = ...,
        between: Global___Int64Range = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "not_in", b"not_in", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "not_in", b"not_in", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "in", "not_in", "between", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___Int64Predicate: _TypeAlias = Int64Predicate  # noqa: Y015

@_typing.final
class BoolPredicate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.bool
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    def __init__(
        self,
        *,
        eq: _builtins.bool = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "is_not_null", b"is_not_null", "is_null", b"is_null", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "is_not_null", b"is_not_null", "is_null", b"is_null", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___BoolPredicate: _TypeAlias = BoolPredicate  # noqa: Y015

@_typing.final
class TimestampPredicate(_message.Message):
    """TimestampPredicate uses google.protobuf.Timestamp. `between` is inclusive.
    Out-of-range timestamps are rejected by the proto codec.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    BETWEEN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    @_builtins.property
    def eq(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def neq(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lte(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def gt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def gte(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def between(self) -> Global___TimestampRange: ...
    def __init__(
        self,
        *,
        eq: _timestamp_pb2.Timestamp = ...,
        neq: _timestamp_pb2.Timestamp = ...,
        lt: _timestamp_pb2.Timestamp = ...,
        lte: _timestamp_pb2.Timestamp = ...,
        gt: _timestamp_pb2.Timestamp = ...,
        gte: _timestamp_pb2.Timestamp = ...,
        between: Global___TimestampRange = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["between", b"between", "eq", b"eq", "gt", b"gt", "gte", b"gte", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "between", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___TimestampPredicate: _TypeAlias = TimestampPredicate  # noqa: Y015

@_typing.final
class BytesPredicate(_message.Message):
    """BytesPredicate covers bytea and (for now) jsonb. JSONB equality is
    byte-for-byte against PG's normalized rendering; value-level JSON
    predicates are not supported yet.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.bytes
    neq: _builtins.bytes
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    def __init__(
        self,
        *,
        eq: _builtins.bytes = ...,
        neq: _builtins.bytes = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "in", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___BytesPredicate: _TypeAlias = BytesPredicate  # noqa: Y015

@_typing.final
class NumericPredicate(_message.Message):
    """NumericPredicate carries numeric/decimal columns as decimal strings;
    the translator casts to PG numeric on both sides of the comparison.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.str
    neq: _builtins.str
    lt: _builtins.str
    lte: _builtins.str
    gt: _builtins.str
    gte: _builtins.str
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    def __init__(
        self,
        *,
        eq: _builtins.str = ...,
        neq: _builtins.str = ...,
        lt: _builtins.str = ...,
        lte: _builtins.str = ...,
        gt: _builtins.str = ...,
        gte: _builtins.str = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "in", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___NumericPredicate: _TypeAlias = NumericPredicate  # noqa: Y015

@_typing.final
class FloatPredicate(_message.Message):
    """FloatPredicate covers `real` (PG float4); DoublePredicate covers `double`
    (float8). Two messages rather than one, and the arm width is the point.

    # Why the widths are kept apart

    float8 is a strict superset of float4, so a single double-carrying message
    would be expressive enough. It would also sit on the wrong side of a real
    hazard: PG promotes a float4 column to float8 to compare it against a float8
    value, and a row storing 0.1 in a `real` column promotes to
    0.10000000149011612. `WHERE score = 0.1::float8` therefore returns nothing
    while the value plainly reads back as 0.1 — measured, not reasoned.

    Carrying the caller's value at the column's own width keeps the comparison
    inside float4. The SQL side casts the placeholder to match (see
    translateFloatPredicate), and pgx independently negotiates the parameter type
    with PG, so today all three agree and any one would do. The width being
    stated in the message is the half a CALLER can see: a client library reading
    this proto binds a float32 for a float4 column without having to know what
    the server does with it.

    # What this does NOT fix

    Float equality is still float equality. `eq` on a value that was computed
    rather than round-tripped from the same literal can miss, on either width.
    The arms exist because a caller who knows their data expects them, not
    because they are safe in general.

    # Ordering is float8, deliberately

    ORDER BY and the keyset cursor compare a `real` column after promotion to
    float8, because the page token carries the promoted value (see
    runtime.EncodePageToken). Filtering therefore compares at float4 and ordering
    at float8. For `double` the two coincide; for `real` they can disagree at the
    boundary, and a PG test pins that a filtered page still returns every matching
    row exactly once.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.float
    neq: _builtins.float
    lt: _builtins.float
    lte: _builtins.float
    gt: _builtins.float
    gte: _builtins.float
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    def __init__(
        self,
        *,
        eq: _builtins.float = ...,
        neq: _builtins.float = ...,
        lt: _builtins.float = ...,
        lte: _builtins.float = ...,
        gt: _builtins.float = ...,
        gte: _builtins.float = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "in", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___FloatPredicate: _TypeAlias = FloatPredicate  # noqa: Y015

@_typing.final
class DoublePredicate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EQ_FIELD_NUMBER: _builtins.int
    NEQ_FIELD_NUMBER: _builtins.int
    LT_FIELD_NUMBER: _builtins.int
    LTE_FIELD_NUMBER: _builtins.int
    GT_FIELD_NUMBER: _builtins.int
    GTE_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    IS_NULL_FIELD_NUMBER: _builtins.int
    IS_NOT_NULL_FIELD_NUMBER: _builtins.int
    eq: _builtins.float
    neq: _builtins.float
    lt: _builtins.float
    lte: _builtins.float
    gt: _builtins.float
    gte: _builtins.float
    is_null: _builtins.bool
    is_not_null: _builtins.bool
    def __init__(
        self,
        *,
        eq: _builtins.float = ...,
        neq: _builtins.float = ...,
        lt: _builtins.float = ...,
        lte: _builtins.float = ...,
        gt: _builtins.float = ...,
        gte: _builtins.float = ...,
        is_null: _builtins.bool = ...,
        is_not_null: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eq", b"eq", "gt", b"gt", "gte", b"gte", "in", b"in", "is_not_null", b"is_not_null", "is_null", b"is_null", "lt", b"lt", "lte", b"lte", "neq", b"neq", "op", b"op"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_op: _TypeAlias = _typing.Literal["eq", "neq", "lt", "lte", "gt", "gte", "in", "is_null", "is_not_null"]  # noqa: Y015
    _WhichOneofArgType_op: _TypeAlias = _typing.Literal["op", b"op"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_op) -> _WhichOneofReturnType_op | None: ...

Global___DoublePredicate: _TypeAlias = DoublePredicate  # noqa: Y015

@_typing.final
class StringList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.str] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StringList: _TypeAlias = StringList  # noqa: Y015

@_typing.final
class Int32List(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.int] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int32List: _TypeAlias = Int32List  # noqa: Y015

@_typing.final
class Int64List(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.int] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int64List: _TypeAlias = Int64List  # noqa: Y015

@_typing.final
class BytesList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.bytes] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BytesList: _TypeAlias = BytesList  # noqa: Y015

@_typing.final
class FloatList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.float] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FloatList: _TypeAlias = FloatList  # noqa: Y015

@_typing.final
class DoubleList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.float] = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DoubleList: _TypeAlias = DoubleList  # noqa: Y015

@_typing.final
class Int32Range(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LO_FIELD_NUMBER: _builtins.int
    HI_FIELD_NUMBER: _builtins.int
    lo: _builtins.int
    hi: _builtins.int
    def __init__(
        self,
        *,
        lo: _builtins.int = ...,
        hi: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hi", b"hi", "lo", b"lo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int32Range: _TypeAlias = Int32Range  # noqa: Y015

@_typing.final
class Int64Range(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LO_FIELD_NUMBER: _builtins.int
    HI_FIELD_NUMBER: _builtins.int
    lo: _builtins.int
    hi: _builtins.int
    def __init__(
        self,
        *,
        lo: _builtins.int = ...,
        hi: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hi", b"hi", "lo", b"lo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int64Range: _TypeAlias = Int64Range  # noqa: Y015

@_typing.final
class TimestampRange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LO_FIELD_NUMBER: _builtins.int
    HI_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def lo(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def hi(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        lo: _timestamp_pb2.Timestamp = ...,
        hi: _timestamp_pb2.Timestamp = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["hi", b"hi", "lo", b"lo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hi", b"hi", "lo", b"lo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TimestampRange: _TypeAlias = TimestampRange  # noqa: Y015
