-- The organisations a session's owner belongs to.
--
-- Copied off the assertion at sign-in, like every other column on this row. The
-- console holds no user record and does not call Cloud at request time, so that
-- Cloud being down does not take a console with it.
--
-- It draws the organisation switcher and nothing else. Do not authorize from
-- this column: it is a snapshot, and a membership revoked at Cloud after
-- sign-in keeps appearing here until the session ends. That is currently free
-- because Cloud's /authorize re-reads cloud.memberships before minting, so a
-- stale entry costs a refusal page and grants nothing.
--
-- TEXT[] rather than a join table. A join table would be the right shape for
-- something queried across sessions; this is read only as part of the row it
-- belongs to, always in whole, and never searched.
--
-- Defaults to empty, which is also what a session opened before this existed
-- carries. A console that reads an empty list shows no switcher, rather than
-- concluding the user belongs nowhere.
ALTER TABLE console.sessions
    ADD COLUMN IF NOT EXISTS orgs TEXT[] NOT NULL DEFAULT '{}';
