-- The address a CALLER reaches this organisation's atlantis at.
--
-- Separate from atl_endpoint, which is the address the CONSOLE dials, for the
-- same reason 0005 added atl_health_addr rather than reusing it. `tide login`
-- hands this to a laptop or a build runner outside the console's network, while
-- the console's route to a tenant's atlantis may be a mesh or VPC address that
-- resolves nowhere else.
--
-- NULL means "the same as atl_endpoint", which is correct for every
-- organisation registered before this migration.
--
-- Resolved by COALESCE at the read site rather than backfilled. A backfill
-- would copy today's value and then diverge the first time atl_endpoint
-- changed, leaving callers pointed at an address nothing updates.
ALTER TABLE console.orgs ADD COLUMN IF NOT EXISTS atl_public_endpoint TEXT;
