-- Each organisation's own certificate signer.
--
-- Migration 0005 gave every organisation its own atlantis behind its own CA,
-- and said why: with a shared authority, a certificate issued for one
-- organisation authenticates at another's server, because caller identity is
-- the common name and caller names are chosen by customers. "backend", "api"
-- and "prod" collide across customers as a matter of course.
--
-- It left one half of that undone. The console still reaches ONE signer, at
-- ATL_SIGNER_ADDR, presenting ONE client certificate — so an organisation with
-- its own authority cannot have a certificate issued for it at all. The code
-- already knows: verifyLeafForOrg refuses the result and says "the signer holds
-- a different certificate authority", which is an accurate message about a
-- system that cannot work rather than a mistake somebody made.
--
-- Four columns, because reaching a signer needs an address, the root that
-- verifies the signer's own certificate, and a client certificate and key to
-- present. None is derivable from another.
--
-- They are read as a group, never column by column. Independent per-column
-- fallback produces mixtures: signer_addr set with signer_client_cert_pem NULL
-- dials the organisation's own signer while presenting the process-wide client
-- certificate, which that signer refuses because SIGNER_CLIENT_CA does not
-- chain it. The mirror case is the mis-issue verifyLeafForOrg catches later.
--
-- All four present means per-organisation. All four absent means the
-- process-wide settings, which is what `make dev-signer` serves. Anything
-- between is an error naming this row, and must not be the "not provisioned"
-- error.
--
-- Nullable, but outside 0005's all-or-nothing gate. store.orgCredentials treats
-- any NULL among 0005's five columns as ErrOrgNotProvisioned, and
-- orgClients.get treats that as an answer: it evicts the cached client and
-- closes the connection, where every other error keeps serving. Widening the
-- gate would de-provision every organisation registered before this migration.
ALTER TABLE console.orgs ADD COLUMN IF NOT EXISTS signer_addr            TEXT;
ALTER TABLE console.orgs ADD COLUMN IF NOT EXISTS signer_ca_pem          TEXT;
ALTER TABLE console.orgs ADD COLUMN IF NOT EXISTS signer_client_cert_pem TEXT;

-- The private half, encrypted, exactly as client_key_ct is.
--
-- Sealed under different associated data from client_key_ct, which uses the
-- organisation name alone. Identical associated data would make the two
-- ciphertexts interchangeable: an UPDATE could copy signer_client_key_ct into
-- client_key_ct and it would decrypt cleanly, leaving the console presenting
-- the signer's client certificate to atlantis.
--
-- Binding to the organisation prevents a key being lifted between
-- organisations, not between columns of one row, so this column's associated
-- data names the field as well.
ALTER TABLE console.orgs ADD COLUMN IF NOT EXISTS signer_client_key_ct   BYTEA;
