-- The header this dropped is not stored anywhere, so it cannot be put back.
--
-- An import is a thirty-day snapshot and its declarations are regenerated by
-- reading the database again. Rewriting the rows to carry a header the emitter
-- no longer produces would leave them disagreeing with every import taken
-- after it.

SELECT 1;
