// Holds three protobuf versions to one number.
//
// The plugin pin decides what every caller's generated Python is produced by.
// The runtime this repository ships in clients/python/_wire, and the floor
// clients/python declares, accommodate it: generated code calls
// ValidateProtobufRuntimeVersion with its own gencode version, so a runtime
// older than the plugin fails at import.
package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

const (
	pyWireDir      = "../../clients/python/src/atlantis_client/_wire"
	pyProjectFile  = "../../clients/python/pyproject.toml"
	minWireModules = 1
)

var (
	pyPluginPin      = regexp.MustCompile(`buf\.build/protocolbuffers/python:v(\d+)\.(\d+)`)
	pyGencodeComment = regexp.MustCompile(`# Protobuf Python Version: (\d+)\.(\d+)\.(\d+)`)
	pyRuntimeCall    = regexp.MustCompile(`ValidateProtobufRuntimeVersion\(\s*_runtime_version\.Domain\.PUBLIC,\s*(\d+),\s*(\d+),\s*(\d+),`)
	pyProtobufFloor  = regexp.MustCompile(`"protobuf>=(\d+\.\d+\.\d+)"`)
)

// TestProtobufFloorMatchesThePluginPin compares the pin, the shipped wire
// modules and the declared floor.
//
// Equality, not compatibility: a floor above what the generated code demands
// excludes runtimes that work, and either direction means the three numbers
// were edited apart.
func TestProtobufFloorMatchesThePluginPin(t *testing.T) {
	pin := pyPluginPin.FindStringSubmatch(pythonBufGen)
	if pin == nil {
		t.Fatalf("pythonBufGen carries no protocolbuffers/python pin")
	}
	pinned := pin[1] + "." + pin[2]

	modules := wireModules(t)
	if len(modules) < minWireModules {
		t.Fatalf("found %d generated wire modules under %s, want at least %d",
			len(modules), pyWireDir, minWireModules)
	}

	for _, path := range modules {
		source := readFile(t, path)

		call := pyRuntimeCall.FindStringSubmatch(source)
		if call == nil {
			t.Errorf("%s: no ValidateProtobufRuntimeVersion call", path)
			continue
		}
		gencode := strings.Join(call[1:4], ".")

		if comment := pyGencodeComment.FindStringSubmatch(source); comment == nil {
			t.Errorf("%s: no gencode version comment", path)
		} else if got := strings.Join(comment[1:4], "."); got != gencode {
			t.Errorf("%s: the header says %s and the runtime check says %s", path, got, gencode)
		}

		if tail := call[2] + "." + call[3]; tail != pinned {
			t.Errorf("%s was generated by protobuf %s, which is not the pinned plugin v%s in cmd/tide/generate.go — regenerate it",
				path, gencode, pinned)
		}

		if floor := protobufFloor(t); floor != gencode {
			t.Errorf("clients/python declares protobuf>=%s and %s needs exactly %s",
				floor, path, gencode)
		}
	}
}

// wireModules lists the committed protobuf output.
func wireModules(t *testing.T) []string {
	t.Helper()
	found, err := filepath.Glob(filepath.Join(pyWireDir, "*_pb2.py"))
	if err != nil {
		t.Fatalf("glob %s: %v", pyWireDir, err)
	}
	return found
}

// protobufFloor reads the declared dependency floor.
func protobufFloor(t *testing.T) string {
	t.Helper()
	m := pyProtobufFloor.FindStringSubmatch(readFile(t, pyProjectFile))
	if m == nil {
		t.Fatalf("%s declares no pinned protobuf floor", pyProjectFile)
	}
	return m[1]
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}
