"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The envelope wrapper for the framed WorkerDispatch stream.

WorkerDispatch carries JSON envelopes over a codec this repository
registers itself, `atl-json-dispatch`, selected by the gRPC content-subtype.
grpc-go forces that subtype with CallContentSubtype; grpc-python cannot —
measured against a live server, it sends `content-type: application/grpc`
with no subtype, call metadata does not override it, and no knob for it
exists in the Python layer or in cygrpc. The server then decodes with the
default proto codec and the stream fails on the first envelope.

So a second service carries the identical JSON envelopes inside a protobuf
message, over the default codec, for clients that cannot choose one. The
bytes inside are byte-for-byte what the unframed stream carries; only the
wrapper differs, and both services run the same session logic.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Frame(_message.Message):
    """Frame wraps one JSON envelope.

    A WorkerEnvelope going up, a DispatchEnvelope coming down — the same tagged
    unions the unframed stream sends, encoded by the same json.Marshal. This
    message never inspects them; it is a length-delimited byte carrier and
    nothing else, which is what keeps the two services from drifting apart on
    envelope shape.
    """

    DESCRIPTOR: _descriptor.Descriptor

    JSON_FIELD_NUMBER: _builtins.int
    json: _builtins.bytes
    def __init__(
        self,
        *,
        json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["json", b"json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Frame: _TypeAlias = Frame  # noqa: Y015
