package atlemit

import (
	"strings"
	"testing"
)

// The header is a file's, not a declaration's.
//
// It opened every entity. The console writes a namespace's tables as one file,
// so a database of 84 tables carried 84 copies of an eight-line comment.

func TestHeaderNamesTheSource(t *testing.T) {
	h := Header("db.example.com:5432")

	if !strings.Contains(h, "db.example.com:5432") {
		t.Errorf("the header does not name where the declarations came from:\n%s", h)
	}
	if !strings.HasPrefix(h, "// Generated by atlantis") {
		t.Errorf("the header does not say what generated the file:\n%s", h)
	}
}

func TestHeaderWithoutASourceStillReads(t *testing.T) {
	h := Header("")
	if strings.Contains(h, "from") {
		t.Errorf("an empty source leaves a dangling clause:\n%s", h)
	}
	if !strings.HasPrefix(h, "// Generated by atlantis") {
		t.Errorf("the header does not say what generated the file:\n%s", h)
	}
}

// One line. Everything the removed text said was either visible in the
// declarations below it or a note that reaches the import's warnings.
func TestHeaderIsOneCommentLine(t *testing.T) {
	h := Header("h:5432")
	lines := strings.Split(strings.TrimRight(h, "\n"), "\n")
	if len(lines) != 1 {
		t.Errorf("the header is %d lines, want 1:\n%s", len(lines), h)
	}
	for _, line := range lines {
		if !strings.HasPrefix(line, "//") {
			t.Errorf("header line is not a comment: %q", line)
		}
	}
}
