#!/usr/bin/env bash
# 30-secrets.sh — the platform's secrets: generated once, kept in Secret
# Manager, materialised as Kubernetes Secrets on every run.
#
#   PROJECT=my-project CLOUD_RESEND_API_KEY=re_... CLOUD_MAIL_FROM=no-reply@example.com ./deploy/gcp/30-secrets.sh
#
# Secret Manager is the source of truth. A value that already exists there is
# reused, so re-running never rotates a data key; losing either data key makes
# every TOTP factor or every organisation permanently unopenable. The
# Kubernetes Secrets are rewritten from Secret Manager each time.
#
# Without a Resend key, MAIL_DEV=1 deploys the logging mailer: verification
# links appear in Cloud's pod log. That is for a first smoke test only.
set -euo pipefail

PROJECT="${PROJECT:-$(gcloud config get-value project 2>/dev/null)}"
ZONE="${ZONE:-us-central1-a}"
CLUSTER="${CLUSTER:-atlantis}"
CTX="gke_${PROJECT}_${ZONE}_${CLUSTER}"
MAIL_DEV="${MAIL_DEV:-}"
cd "$(dirname "$0")/../.."

k() { kubectl --context "$CTX" "$@"; }

# gsm_get prints the latest version of a secret, or nothing.
gsm_get() { gcloud secrets versions access latest --secret "$1" --project "$PROJECT" 2>/dev/null || true; }
# gsm_put_once stores a value only when the secret does not exist yet.
gsm_put_once() {
    local name="$1" value="$2"
    if gcloud secrets describe "$name" --project "$PROJECT" >/dev/null 2>&1; then
        return 0
    fi
    gcloud secrets create "$name" --project "$PROJECT" --replication-policy=automatic >/dev/null
    printf '%s' "$value" | gcloud secrets versions add "$name" --project "$PROJECT" --data-file=- >/dev/null
    echo "  created $name"
}

echo "==> generating what does not exist yet"
gsm_put_once atlantis-cloud-data-key "$(go run ./cmd/cloud data-key 2>/dev/null)"
gsm_put_once atlantis-console-data-key "$(go run ./cmd/cloud data-key 2>/dev/null)"
tmpkey="$(mktemp)"; trap 'rm -f "$tmpkey"' EXIT
rm -f "$tmpkey"; go run ./cmd/cloud signing-key -path "$tmpkey" >/dev/null
gsm_put_once atlantis-cloud-signing-key "$(cat "$tmpkey")"
gsm_put_once atlantis-console-session-secret "$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)"

# The database passwords were generated by bootstrap.sh and live in the
# cluster; the connection strings are recorded here so they survive it.
cloud_pw="$(k -n atlantis-system get secret control-db-cloud -o jsonpath='{.data.password}' | base64 -d)"
console_pw="$(k -n atlantis-system get secret control-db-console -o jsonpath='{.data.password}' | base64 -d)"
host="control-rw.atlantis-system.svc.cluster.local"
gsm_put_once atlantis-cloud-pg-url "postgres://atlantis_cloud:${cloud_pw}@${host}:5432/atlantis?sslmode=require"
gsm_put_once atlantis-console-pg-url "postgres://atlantis_console:${console_pw}@${host}:5432/atlantis?sslmode=require"

if [ -n "${CLOUD_RESEND_API_KEY:-}" ]; then
    gsm_put_once atlantis-resend-api-key "$CLOUD_RESEND_API_KEY"
fi
resend="$(gsm_get atlantis-resend-api-key)"

# Analytics. Optional: with no key the ingestion route answers 404 and every
# server-side sink discards.
#
# Written on every run, unlike the data keys: this one belongs to a third party
# and is rotated there, so gsm_put_once would keep a revoked value and report
# success. Passing an empty CLOUD_POSTHOG_KEY does not erase it; delete the
# secret to turn analytics off.
if [ -n "${CLOUD_POSTHOG_KEY:-}" ]; then
    if ! gcloud secrets describe atlantis-posthog-key --project "$PROJECT" >/dev/null 2>&1; then
        gcloud secrets create atlantis-posthog-key --project "$PROJECT" --replication-policy=automatic >/dev/null
    fi
    printf '%s' "$CLOUD_POSTHOG_KEY" | gcloud secrets versions add atlantis-posthog-key --project "$PROJECT" --data-file=- >/dev/null
fi
posthog="$(gsm_get atlantis-posthog-key)"

if [ -z "$resend" ] && [ -z "$MAIL_DEV" ]; then
    echo "no Resend key in Secret Manager. Pass CLOUD_RESEND_API_KEY=..., or MAIL_DEV=1 for the logging mailer." >&2
    exit 1
fi

echo "==> Kubernetes Secrets in atlantis-system"
k -n atlantis-system create secret generic atlantis-cloud \
    --from-literal=CLOUD_PG_URL="$(gsm_get atlantis-cloud-pg-url)" \
    --from-literal=CLOUD_DATA_KEY="$(gsm_get atlantis-cloud-data-key)" \
    --from-literal=CLOUD_RESEND_API_KEY="$resend" \
    --from-literal=CLOUD_POSTHOG_KEY="$posthog" \
    --from-literal=signing-key.pem="$(gsm_get atlantis-cloud-signing-key)" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
k -n atlantis-system create secret generic atlantis-console \
    --from-literal=CONSOLE_PG_URL="$(gsm_get atlantis-console-pg-url)" \
    --from-literal=CONSOLE_DATA_KEY="$(gsm_get atlantis-console-data-key)" \
    --from-literal=CONSOLE_SESSION_SECRET="$(gsm_get atlantis-console-session-secret)" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
k -n atlantis-system create secret generic atlantis-provisioner \
    --from-literal=CLOUD_PG_URL="$(gsm_get atlantis-cloud-pg-url)" \
    --from-literal=CONSOLE_PG_URL="$(gsm_get atlantis-console-pg-url)" \
    --from-literal=CONSOLE_DATA_KEY="$(gsm_get atlantis-console-data-key)" \
    --from-literal=CLOUD_POSTHOG_KEY="$posthog" \
    --dry-run=client -o yaml | k apply -f - >/dev/null
k -n atlantis-system get secret atlantis-cloud atlantis-console atlantis-provisioner

echo
echo "secrets in place. mail: $([ -n "$resend" ] && echo "Resend" || echo "logging mailer (MAIL_DEV)")"
echo "                 analytics: $([ -n "$posthog" ] && echo "PostHog" || echo "off (no CLOUD_POSTHOG_KEY)")"
