# Code generated by tide. DO NOT EDIT.
"""The typed Python client for this schema.

One subpackage per namespace:

    atlantis.library.v1

The runtime these import is the atlantis-client distribution.
"""
